# Dependabot helps update dependencies to keep them up-to-date.
# Configuration docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    reviewers:
      - "customerio/mobile"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-action-dependencies:
        patterns:
        - "*"
