# Rules: https://realm.github.io/SwiftLint/rule-directory.html

excluded: # paths to ignore during linting. Takes precedence over `included`.  
  - .build
  - Package.swift
reporter: "emoji" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)