// Generated using Sourcery 2.0.3 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// swiftlint:disable all

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
#if canImport(UserNotifications)
import UserNotifications
#endif
import CioInternalCommon

/**
 ######################################################
 Documentation
 ######################################################

 This automatically generated file you are viewing contains mock classes that you can use in your test suite.

 * How do you generate a new mock class?

 1. Mocks are generated from Swift protocols. So, you must make one.

 ```
 protocol FriendsRepository {
     func acceptFriendRequest<Attributes: Encodable>(attributes: Attributes, _ onComplete: @escaping () -> Void)
 }

 class AppFriendsRepository: FriendsRepository {
     ...
 }
 ```

 2. Have your new protocol extend `AutoMockable`:

 ```
 protocol FriendsRepository: AutoMockable {
     func acceptFriendRequest<Attributes: Encodable>(
         // sourcery:Type=Encodable
         attributes: Attributes,
         _ onComplete: @escaping () -> Void)
 }
 ```

 > Notice the use of `// sourcery:Type=Encodable` for the generic type parameter. Without this, the mock would
 fail to compile: `functionNameReceiveArguments = (Attributes)` because `Attributes` is unknown to this `var`.
 Instead, we give the parameter a different type to use for the mock. `Encodable` works in this case.
 It will require a cast in the test function code, however.

 3. Run the command `make generate` on your machine. The new mock should be added to this file.

 * How do you use the mocks in your test class?

 ```
 class ExampleViewModelTest: XCTestCase {
     var viewModel: ExampleViewModel!
     var exampleRepositoryMock: ExampleRepositoryMock!
     override func setUp() {
         exampleRepositoryMock = ExampleRepositoryMock()
         viewModel = AppExampleViewModel(exampleRepository: exampleRepositoryMock)
     }
 }
 ```

 Or, you may need to inject the mock in a different way using the DI.shared graph:

 ```
 class ExampleTest: XCTestCase {
     var exampleViewModelMock: ExampleViewModelMock!
     var example: Example!
     override func setUp() {
         exampleViewModelMock = ExampleViewModelMock()
         DI.shared.override(.exampleViewModel, value: exampleViewModelMock, forType: ExampleViewModel.self)
         example = Example()
     }
 }

 ```

 */

/**
 Class to easily create a mocked version of the `GistInstance` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class GistInstanceMock: GistInstance, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {
        Mocks.shared.add(mock: self)
    }

    public func resetMock() {
        showMessageCallsCount = 0
        showMessageReceivedArguments = nil
        showMessageReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - showMessage

    /// Number of times the function was called.
    @Atomic private(set) var showMessageCallsCount = 0
    /// `true` if the function was ever called.
    var showMessageCalled: Bool {
        showMessageCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var showMessageReceivedArguments: (message: Message, position: MessagePosition)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var showMessageReceivedInvocations: [(message: Message, position: MessagePosition)] = []
    /// Value to return from the mocked function.
    var showMessageReturnValue: Bool!
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     The closure has first priority to return a value for the mocked function. If the closure returns `nil`,
     then the mock will attempt to return the value for `showMessageReturnValue`
     */
    var showMessageClosure: ((Message, MessagePosition) -> Bool)?

    /// Mocked function for `showMessage(_ message: Message, position: MessagePosition)`. Your opportunity to return a mocked value and check result of mock in test code.
    func showMessage(_ message: Message, position: MessagePosition) -> Bool {
        mockCalled = true
        showMessageCallsCount += 1
        showMessageReceivedArguments = (message: message, position: position)
        showMessageReceivedInvocations.append((message: message, position: position))
        return showMessageClosure.map { $0(message, position) } ?? showMessageReturnValue
    }
}

/**
 Class to easily create a mocked version of the `InAppEventListener` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
public class InAppEventListenerMock: InAppEventListener, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    public var mockCalled: Bool = false //

    public init() {
        Mocks.shared.add(mock: self)
    }

    public func resetMock() {
        messageShownCallsCount = 0
        messageShownReceivedArguments = nil
        messageShownReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        messageDismissedCallsCount = 0
        messageDismissedReceivedArguments = nil
        messageDismissedReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        errorWithMessageCallsCount = 0
        errorWithMessageReceivedArguments = nil
        errorWithMessageReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        messageActionTakenCallsCount = 0
        messageActionTakenReceivedArguments = nil
        messageActionTakenReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - messageShown

    /// Number of times the function was called.
    @Atomic public private(set) var messageShownCallsCount = 0
    /// `true` if the function was ever called.
    public var messageShownCalled: Bool {
        messageShownCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic public private(set) var messageShownReceivedArguments: InAppMessage?
    /// Arguments from *all* of the times that the function was called.
    @Atomic public private(set) var messageShownReceivedInvocations: [InAppMessage] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var messageShownClosure: ((InAppMessage) -> Void)?

    /// Mocked function for `messageShown(message: InAppMessage)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func messageShown(message: InAppMessage) {
        mockCalled = true
        messageShownCallsCount += 1
        messageShownReceivedArguments = message
        messageShownReceivedInvocations.append(message)
        messageShownClosure?(message)
    }

    // MARK: - messageDismissed

    /// Number of times the function was called.
    @Atomic public private(set) var messageDismissedCallsCount = 0
    /// `true` if the function was ever called.
    public var messageDismissedCalled: Bool {
        messageDismissedCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic public private(set) var messageDismissedReceivedArguments: InAppMessage?
    /// Arguments from *all* of the times that the function was called.
    @Atomic public private(set) var messageDismissedReceivedInvocations: [InAppMessage] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var messageDismissedClosure: ((InAppMessage) -> Void)?

    /// Mocked function for `messageDismissed(message: InAppMessage)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func messageDismissed(message: InAppMessage) {
        mockCalled = true
        messageDismissedCallsCount += 1
        messageDismissedReceivedArguments = message
        messageDismissedReceivedInvocations.append(message)
        messageDismissedClosure?(message)
    }

    // MARK: - errorWithMessage

    /// Number of times the function was called.
    @Atomic public private(set) var errorWithMessageCallsCount = 0
    /// `true` if the function was ever called.
    public var errorWithMessageCalled: Bool {
        errorWithMessageCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic public private(set) var errorWithMessageReceivedArguments: InAppMessage?
    /// Arguments from *all* of the times that the function was called.
    @Atomic public private(set) var errorWithMessageReceivedInvocations: [InAppMessage] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var errorWithMessageClosure: ((InAppMessage) -> Void)?

    /// Mocked function for `errorWithMessage(message: InAppMessage)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func errorWithMessage(message: InAppMessage) {
        mockCalled = true
        errorWithMessageCallsCount += 1
        errorWithMessageReceivedArguments = message
        errorWithMessageReceivedInvocations.append(message)
        errorWithMessageClosure?(message)
    }

    // MARK: - messageActionTaken

    /// Number of times the function was called.
    @Atomic public private(set) var messageActionTakenCallsCount = 0
    /// `true` if the function was ever called.
    public var messageActionTakenCalled: Bool {
        messageActionTakenCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic public private(set) var messageActionTakenReceivedArguments: (message: InAppMessage, actionValue: String, actionName: String)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic public private(set) var messageActionTakenReceivedInvocations: [(message: InAppMessage, actionValue: String, actionName: String)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var messageActionTakenClosure: ((InAppMessage, String, String) -> Void)?

    /// Mocked function for `messageActionTaken(message: InAppMessage, actionValue: String, actionName: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func messageActionTaken(message: InAppMessage, actionValue: String, actionName: String) {
        mockCalled = true
        messageActionTakenCallsCount += 1
        messageActionTakenReceivedArguments = (message: message, actionValue: actionValue, actionName: actionName)
        messageActionTakenReceivedInvocations.append((message: message, actionValue: actionValue, actionName: actionName))
        messageActionTakenClosure?(message, actionValue, actionName)
    }
}

/**
 Class to easily create a mocked version of the `InAppProvider` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class InAppProviderMock: InAppProvider, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {
        Mocks.shared.add(mock: self)
    }

    public func resetMock() {
        initializeCallsCount = 0
        initializeReceivedArguments = nil
        initializeReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        setProfileIdentifierCallsCount = 0
        setProfileIdentifierReceivedArguments = nil
        setProfileIdentifierReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        clearIdentifyCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
        setRouteCallsCount = 0
        setRouteReceivedArguments = nil
        setRouteReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        dismissMessageCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - initialize

    /// Number of times the function was called.
    @Atomic private(set) var initializeCallsCount = 0
    /// `true` if the function was ever called.
    var initializeCalled: Bool {
        initializeCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var initializeReceivedArguments: (siteId: String, region: Region, delegate: GistDelegate, enableLogging: Bool)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var initializeReceivedInvocations: [(siteId: String, region: Region, delegate: GistDelegate, enableLogging: Bool)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var initializeClosure: ((String, Region, GistDelegate, Bool) -> Void)?

    /// Mocked function for `initialize(siteId: String, region: Region, delegate: GistDelegate, enableLogging: Bool)`. Your opportunity to return a mocked value and check result of mock in test code.
    func initialize(siteId: String, region: Region, delegate: GistDelegate, enableLogging: Bool) {
        mockCalled = true
        initializeCallsCount += 1
        initializeReceivedArguments = (siteId: siteId, region: region, delegate: delegate, enableLogging: enableLogging)
        initializeReceivedInvocations.append((siteId: siteId, region: region, delegate: delegate, enableLogging: enableLogging))
        initializeClosure?(siteId, region, delegate, enableLogging)
    }

    // MARK: - setProfileIdentifier

    /// Number of times the function was called.
    @Atomic private(set) var setProfileIdentifierCallsCount = 0
    /// `true` if the function was ever called.
    var setProfileIdentifierCalled: Bool {
        setProfileIdentifierCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var setProfileIdentifierReceivedArguments: String?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var setProfileIdentifierReceivedInvocations: [String] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var setProfileIdentifierClosure: ((String) -> Void)?

    /// Mocked function for `setProfileIdentifier(_ id: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    func setProfileIdentifier(_ id: String) {
        mockCalled = true
        setProfileIdentifierCallsCount += 1
        setProfileIdentifierReceivedArguments = id
        setProfileIdentifierReceivedInvocations.append(id)
        setProfileIdentifierClosure?(id)
    }

    // MARK: - clearIdentify

    /// Number of times the function was called.
    @Atomic private(set) var clearIdentifyCallsCount = 0
    /// `true` if the function was ever called.
    var clearIdentifyCalled: Bool {
        clearIdentifyCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var clearIdentifyClosure: (() -> Void)?

    /// Mocked function for `clearIdentify()`. Your opportunity to return a mocked value and check result of mock in test code.
    func clearIdentify() {
        mockCalled = true
        clearIdentifyCallsCount += 1
        clearIdentifyClosure?()
    }

    // MARK: - setRoute

    /// Number of times the function was called.
    @Atomic private(set) var setRouteCallsCount = 0
    /// `true` if the function was ever called.
    var setRouteCalled: Bool {
        setRouteCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var setRouteReceivedArguments: String?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var setRouteReceivedInvocations: [String] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var setRouteClosure: ((String) -> Void)?

    /// Mocked function for `setRoute(_ route: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    func setRoute(_ route: String) {
        mockCalled = true
        setRouteCallsCount += 1
        setRouteReceivedArguments = route
        setRouteReceivedInvocations.append(route)
        setRouteClosure?(route)
    }

    // MARK: - dismissMessage

    /// Number of times the function was called.
    @Atomic private(set) var dismissMessageCallsCount = 0
    /// `true` if the function was ever called.
    var dismissMessageCalled: Bool {
        dismissMessageCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var dismissMessageClosure: (() -> Void)?

    /// Mocked function for `dismissMessage()`. Your opportunity to return a mocked value and check result of mock in test code.
    func dismissMessage() {
        mockCalled = true
        dismissMessageCallsCount += 1
        dismissMessageClosure?()
    }
}

/**
 Class to easily create a mocked version of the `MessageQueueManager` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class MessageQueueManagerMock: MessageQueueManager, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {
        Mocks.shared.add(mock: self)
    }

    /**
     When setter of the property called, the value given to setter is set here.
     When the getter of the property called, the value set here will be returned. Your chance to mock the property.
     */
    var underlyingInterval: Double!
    /// `true` if the getter or setter of property is called at least once.
    var intervalCalled: Bool {
        intervalGetCalled || intervalSetCalled
    }

    /// `true` if the getter called on the property at least once.
    var intervalGetCalled: Bool {
        intervalGetCallsCount > 0
    }

    var intervalGetCallsCount = 0
    /// `true` if the setter called on the property at least once.
    var intervalSetCalled: Bool {
        intervalSetCallsCount > 0
    }

    var intervalSetCallsCount = 0
    /// The mocked property with a getter and setter.
    var interval: Double {
        get {
            mockCalled = true
            intervalGetCallsCount += 1
            return underlyingInterval
        }
        set(value) {
            mockCalled = true
            intervalSetCallsCount += 1
            underlyingInterval = value
        }
    }

    public func resetMock() {
        intervalGetCallsCount = 0
        intervalSetCallsCount = 0
        setupCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
        setupSkipQueueCheckReceivedArguments = nil
        setupSkipQueueCheckReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        fetchUserMessagesFromLocalStoreCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
        removeMessageFromLocalStoreCallsCount = 0
        removeMessageFromLocalStoreReceivedArguments = nil
        removeMessageFromLocalStoreReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        clearUserMessagesFromLocalStoreCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
        getInlineMessagesCallsCount = 0
        getInlineMessagesReceivedArguments = nil
        getInlineMessagesReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - setup

    /// Number of times the function was called.
    @Atomic private(set) var setupCallsCount = 0
    /// `true` if the function was ever called.
    var setupCalled: Bool {
        setupCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var setupClosure: (() -> Void)?

    /// Mocked function for `setup()`. Your opportunity to return a mocked value and check result of mock in test code.
    func setup() {
        mockCalled = true
        setupCallsCount += 1
        setupClosure?()
    }

    // MARK: - setup

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var setupSkipQueueCheckReceivedArguments: Bool?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var setupSkipQueueCheckReceivedInvocations: [Bool] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var setupSkipQueueCheckClosure: ((Bool) -> Void)?

    /// Mocked function for `setup(skipQueueCheck: Bool)`. Your opportunity to return a mocked value and check result of mock in test code.
    func setup(skipQueueCheck: Bool) {
        mockCalled = true
        setupCallsCount += 1
        setupSkipQueueCheckReceivedArguments = skipQueueCheck
        setupSkipQueueCheckReceivedInvocations.append(skipQueueCheck)
        setupSkipQueueCheckClosure?(skipQueueCheck)
    }

    // MARK: - fetchUserMessagesFromLocalStore

    /// Number of times the function was called.
    @Atomic private(set) var fetchUserMessagesFromLocalStoreCallsCount = 0
    /// `true` if the function was ever called.
    var fetchUserMessagesFromLocalStoreCalled: Bool {
        fetchUserMessagesFromLocalStoreCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var fetchUserMessagesFromLocalStoreClosure: (() -> Void)?

    /// Mocked function for `fetchUserMessagesFromLocalStore()`. Your opportunity to return a mocked value and check result of mock in test code.
    func fetchUserMessagesFromLocalStore() {
        mockCalled = true
        fetchUserMessagesFromLocalStoreCallsCount += 1
        fetchUserMessagesFromLocalStoreClosure?()
    }

    // MARK: - removeMessageFromLocalStore

    /// Number of times the function was called.
    @Atomic private(set) var removeMessageFromLocalStoreCallsCount = 0
    /// `true` if the function was ever called.
    var removeMessageFromLocalStoreCalled: Bool {
        removeMessageFromLocalStoreCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var removeMessageFromLocalStoreReceivedArguments: Message?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var removeMessageFromLocalStoreReceivedInvocations: [Message] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var removeMessageFromLocalStoreClosure: ((Message) -> Void)?

    /// Mocked function for `removeMessageFromLocalStore(message: Message)`. Your opportunity to return a mocked value and check result of mock in test code.
    func removeMessageFromLocalStore(message: Message) {
        mockCalled = true
        removeMessageFromLocalStoreCallsCount += 1
        removeMessageFromLocalStoreReceivedArguments = message
        removeMessageFromLocalStoreReceivedInvocations.append(message)
        removeMessageFromLocalStoreClosure?(message)
    }

    // MARK: - clearUserMessagesFromLocalStore

    /// Number of times the function was called.
    @Atomic private(set) var clearUserMessagesFromLocalStoreCallsCount = 0
    /// `true` if the function was ever called.
    var clearUserMessagesFromLocalStoreCalled: Bool {
        clearUserMessagesFromLocalStoreCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var clearUserMessagesFromLocalStoreClosure: (() -> Void)?

    /// Mocked function for `clearUserMessagesFromLocalStore()`. Your opportunity to return a mocked value and check result of mock in test code.
    func clearUserMessagesFromLocalStore() {
        mockCalled = true
        clearUserMessagesFromLocalStoreCallsCount += 1
        clearUserMessagesFromLocalStoreClosure?()
    }

    // MARK: - getInlineMessages

    /// Number of times the function was called.
    @Atomic private(set) var getInlineMessagesCallsCount = 0
    /// `true` if the function was ever called.
    var getInlineMessagesCalled: Bool {
        getInlineMessagesCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var getInlineMessagesReceivedArguments: String?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var getInlineMessagesReceivedInvocations: [String] = []
    /// Value to return from the mocked function.
    var getInlineMessagesReturnValue: [Message]!
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     The closure has first priority to return a value for the mocked function. If the closure returns `nil`,
     then the mock will attempt to return the value for `getInlineMessagesReturnValue`
     */
    var getInlineMessagesClosure: ((String) -> [Message])?

    /// Mocked function for `getInlineMessages(forElementId elementId: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    func getInlineMessages(forElementId elementId: String) -> [Message] {
        mockCalled = true
        getInlineMessagesCallsCount += 1
        getInlineMessagesReceivedArguments = elementId
        getInlineMessagesReceivedInvocations.append(elementId)
        return getInlineMessagesClosure.map { $0(elementId) } ?? getInlineMessagesReturnValue
    }
}

/**
 Class to easily create a mocked version of the `MessagingInAppInstance` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
public class MessagingInAppInstanceMock: MessagingInAppInstance, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    public var mockCalled: Bool = false //

    public init() {
        Mocks.shared.add(mock: self)
    }

    public func resetMock() {
        setEventListenerCallsCount = 0
        setEventListenerReceivedArguments = nil
        setEventListenerReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        dismissMessageCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - setEventListener

    /// Number of times the function was called.
    @Atomic public private(set) var setEventListenerCallsCount = 0
    /// `true` if the function was ever called.
    public var setEventListenerCalled: Bool {
        setEventListenerCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic public private(set) var setEventListenerReceivedArguments: InAppEventListener??
    /// Arguments from *all* of the times that the function was called.
    @Atomic public private(set) var setEventListenerReceivedInvocations: [InAppEventListener?] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var setEventListenerClosure: ((InAppEventListener?) -> Void)?

    /// Mocked function for `setEventListener(_ eventListener: InAppEventListener?)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func setEventListener(_ eventListener: InAppEventListener?) {
        mockCalled = true
        setEventListenerCallsCount += 1
        setEventListenerReceivedArguments = eventListener
        setEventListenerReceivedInvocations.append(eventListener)
        setEventListenerClosure?(eventListener)
    }

    // MARK: - dismissMessage

    /// Number of times the function was called.
    @Atomic public private(set) var dismissMessageCallsCount = 0
    /// `true` if the function was ever called.
    public var dismissMessageCalled: Bool {
        dismissMessageCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var dismissMessageClosure: (() -> Void)?

    /// Mocked function for `dismissMessage()`. Your opportunity to return a mocked value and check result of mock in test code.
    public func dismissMessage() {
        mockCalled = true
        dismissMessageCallsCount += 1
        dismissMessageClosure?()
    }
}

// swiftlint:enable all
