// Generated using Sourcery 2.0.3 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// swiftlint:disable all

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
#if canImport(UserNotifications)
import UserNotifications
#endif
import CioInternalCommon

/**
 ######################################################
 Documentation
 ######################################################

 This automatically generated file you are viewing contains mock classes that you can use in your test suite.

 * How do you generate a new mock class?

 1. Mocks are generated from Swift protocols. So, you must make one.

 ```
 protocol FriendsRepository {
     func acceptFriendRequest<Attributes: Encodable>(attributes: Attributes, _ onComplete: @escaping () -> Void)
 }

 class AppFriendsRepository: FriendsRepository {
     ...
 }
 ```

 2. Have your new protocol extend `AutoMockable`:

 ```
 protocol FriendsRepository: AutoMockable {
     func acceptFriendRequest<Attributes: Encodable>(
         // sourcery:Type=Encodable
         attributes: Attributes,
         _ onComplete: @escaping () -> Void)
 }
 ```

 > Notice the use of `// sourcery:Type=Encodable` for the generic type parameter. Without this, the mock would
 fail to compile: `functionNameReceiveArguments = (Attributes)` because `Attributes` is unknown to this `var`.
 Instead, we give the parameter a different type to use for the mock. `Encodable` works in this case.
 It will require a cast in the test function code, however.

 3. Run the command `make generate` on your machine. The new mock should be added to this file.

 * How do you use the mocks in your test class?

 ```
 class ExampleViewModelTest: XCTestCase {
     var viewModel: ExampleViewModel!
     var exampleRepositoryMock: ExampleRepositoryMock!
     override func setUp() {
         exampleRepositoryMock = ExampleRepositoryMock()
         viewModel = AppExampleViewModel(exampleRepository: exampleRepositoryMock)
     }
 }
 ```

 Or, you may need to inject the mock in a different way using the DI.shared graph:

 ```
 class ExampleTest: XCTestCase {
     var exampleViewModelMock: ExampleViewModelMock!
     var example: Example!
     override func setUp() {
         exampleViewModelMock = ExampleViewModelMock()
         DI.shared.override(.exampleViewModel, value: exampleViewModelMock, forType: ExampleViewModel.self)
         example = Example()
     }
 }

 ```

 */

/**
 Class to easily create a mocked version of the `GeofenceApiService` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class GeofenceApiServiceMock: GeofenceApiService, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {}

    public func resetMock() {
        fetchGeofencesCallsCount = 0
        fetchGeofencesReceivedArguments = nil
        fetchGeofencesReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - fetchGeofences

    /// Number of times the function was called.
    @Atomic private(set) var fetchGeofencesCallsCount = 0
    /// `true` if the function was ever called.
    var fetchGeofencesCalled: Bool {
        fetchGeofencesCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var fetchGeofencesReceivedArguments: (latitude: Double, longitude: Double, completion: (Result<GeofenceApiResponse, GeofenceApiError>) -> Void)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var fetchGeofencesReceivedInvocations: [(latitude: Double, longitude: Double, completion: (Result<GeofenceApiResponse, GeofenceApiError>) -> Void)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var fetchGeofencesClosure: ((Double, Double, @escaping (Result<GeofenceApiResponse, GeofenceApiError>) -> Void) -> Void)?

    /// Mocked function for `fetchGeofences(latitude: Double, longitude: Double, completion: @escaping (Result<GeofenceApiResponse, GeofenceApiError>) -> Void)`. Your opportunity to return a mocked value and check result of mock in test code.
    func fetchGeofences(latitude: Double, longitude: Double, completion: @escaping (Result<GeofenceApiResponse, GeofenceApiError>) -> Void) {
        mockCalled = true
        fetchGeofencesCallsCount += 1
        fetchGeofencesReceivedArguments = (latitude: latitude, longitude: longitude, completion: completion)
        fetchGeofencesReceivedInvocations.append((latitude: latitude, longitude: longitude, completion: completion))
        fetchGeofencesClosure?(latitude, longitude, completion)
    }
}

/**
 Class to easily create a mocked version of the `GeofenceDeliveryTracker` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class GeofenceDeliveryTrackerMock: GeofenceDeliveryTracker, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {}

    public func resetMock() {
        deliverCallsCount = 0
        deliverReceivedArguments = nil
        deliverReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - deliver

    /// Number of times the function was called.
    @Atomic private(set) var deliverCallsCount = 0
    /// `true` if the function was ever called.
    var deliverCalled: Bool {
        deliverCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var deliverReceivedArguments: (metric: PendingGeofenceMetric, userId: String, onComplete: (Result<Void, BackgroundDeliveryHttpError>) -> Void)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var deliverReceivedInvocations: [(metric: PendingGeofenceMetric, userId: String, onComplete: (Result<Void, BackgroundDeliveryHttpError>) -> Void)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var deliverClosure: ((PendingGeofenceMetric, String, @escaping (Result<Void, BackgroundDeliveryHttpError>) -> Void) -> Void)?

    /// Mocked function for `deliver(metric: PendingGeofenceMetric, userId: String, onComplete: @escaping (Result<Void, BackgroundDeliveryHttpError>) -> Void)`. Your opportunity to return a mocked value and check result of mock in test code.
    func deliver(metric: PendingGeofenceMetric, userId: String, onComplete: @escaping (Result<Void, BackgroundDeliveryHttpError>) -> Void) {
        mockCalled = true
        deliverCallsCount += 1
        deliverReceivedArguments = (metric: metric, userId: userId, onComplete: onComplete)
        deliverReceivedInvocations.append((metric: metric, userId: userId, onComplete: onComplete))
        deliverClosure?(metric, userId, onComplete)
    }
}

/**
 Class to easily create a mocked version of the `GeofenceSyncCoordinator` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class GeofenceSyncCoordinatorMock: GeofenceSyncCoordinator, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {}

    public func resetMock() {
        refreshCallsCount = 0
        refreshReceivedArguments = nil
        refreshReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        applyCachedRegistrationCallsCount = 0
        applyCachedRegistrationReceivedArguments = nil
        applyCachedRegistrationReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - refresh

    /// Number of times the function was called.
    @Atomic private(set) var refreshCallsCount = 0
    /// `true` if the function was ever called.
    var refreshCalled: Bool {
        refreshCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var refreshReceivedArguments: (latitude: Double, longitude: Double)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var refreshReceivedInvocations: [(latitude: Double, longitude: Double)] = []
    /// Value to return from the mocked function.
    var refreshReturnValue: Result<Void, GeofenceSyncError>!
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     The closure has first priority to return a value for the mocked function. If the closure returns `nil`,
     then the mock will attempt to return the value for `refreshReturnValue`
     */
    var refreshClosure: ((Double, Double) -> Result<Void, GeofenceSyncError>)?

    /// Mocked function for `refresh(latitude: Double, longitude: Double)`. Your opportunity to return a mocked value and check result of mock in test code.
    func refresh(latitude: Double, longitude: Double) -> Result<Void, GeofenceSyncError> {
        mockCalled = true
        refreshCallsCount += 1
        refreshReceivedArguments = (latitude: latitude, longitude: longitude)
        refreshReceivedInvocations.append((latitude: latitude, longitude: longitude))
        return refreshClosure.map { $0(latitude, longitude) } ?? refreshReturnValue
    }

    // MARK: - applyCachedRegistration

    /// Number of times the function was called.
    @Atomic private(set) var applyCachedRegistrationCallsCount = 0
    /// `true` if the function was ever called.
    var applyCachedRegistrationCalled: Bool {
        applyCachedRegistrationCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var applyCachedRegistrationReceivedArguments: (cachedRegions: [Geofence], anchor: LocationData?, config: GeofenceConfig?, userId: String?)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var applyCachedRegistrationReceivedInvocations: [(cachedRegions: [Geofence], anchor: LocationData?, config: GeofenceConfig?, userId: String?)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var applyCachedRegistrationClosure: (([Geofence], LocationData?, GeofenceConfig?, String?) -> Void)?

    /// Mocked function for `applyCachedRegistration(cachedRegions: [Geofence], anchor: LocationData?, config: GeofenceConfig?, userId: String?)`. Your opportunity to return a mocked value and check result of mock in test code.
    @MainActor
    func applyCachedRegistration(cachedRegions: [Geofence], anchor: LocationData?, config: GeofenceConfig?, userId: String?) {
        mockCalled = true
        applyCachedRegistrationCallsCount += 1
        applyCachedRegistrationReceivedArguments = (cachedRegions: cachedRegions, anchor: anchor, config: config, userId: userId)
        applyCachedRegistrationReceivedInvocations.append((cachedRegions: cachedRegions, anchor: anchor, config: config, userId: userId))
        applyCachedRegistrationClosure?(cachedRegions, anchor, config, userId)
    }
}

// swiftlint:enable all
