// Generated using Sourcery 2.0.3 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// swiftlint:disable all

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
#if canImport(UserNotifications)
import UserNotifications
#endif
import CioInternalCommon
import CoreLocation

/**
 ######################################################
 Documentation
 ######################################################

 This automatically generated file you are viewing contains mock classes that you can use in your test suite.

 * How do you generate a new mock class?

 1. Mocks are generated from Swift protocols. So, you must make one.

 ```
 protocol FriendsRepository {
     func acceptFriendRequest<Attributes: Encodable>(attributes: Attributes, _ onComplete: @escaping () -> Void)
 }

 class AppFriendsRepository: FriendsRepository {
     ...
 }
 ```

 2. Have your new protocol extend `AutoMockable`:

 ```
 protocol FriendsRepository: AutoMockable {
     func acceptFriendRequest<Attributes: Encodable>(
         // sourcery:Type=Encodable
         attributes: Attributes,
         _ onComplete: @escaping () -> Void)
 }
 ```

 > Notice the use of `// sourcery:Type=Encodable` for the generic type parameter. Without this, the mock would
 fail to compile: `functionNameReceiveArguments = (Attributes)` because `Attributes` is unknown to this `var`.
 Instead, we give the parameter a different type to use for the mock. `Encodable` works in this case.
 It will require a cast in the test function code, however.

 3. Run the command `make generate` on your machine. The new mock should be added to this file.

 * How do you use the mocks in your test class?

 ```
 class ExampleViewModelTest: XCTestCase {
     var viewModel: ExampleViewModel!
     var exampleRepositoryMock: ExampleRepositoryMock!
     override func setUp() {
         exampleRepositoryMock = ExampleRepositoryMock()
         viewModel = AppExampleViewModel(exampleRepository: exampleRepositoryMock)
     }
 }
 ```

 Or, you may need to inject the mock in a different way using the DI.shared graph:

 ```
 class ExampleTest: XCTestCase {
     var exampleViewModelMock: ExampleViewModelMock!
     var example: Example!
     override func setUp() {
         exampleViewModelMock = ExampleViewModelMock()
         DI.shared.override(.exampleViewModel, value: exampleViewModelMock, forType: ExampleViewModel.self)
         example = Example()
     }
 }

 ```

 */

/**
 Class to easily create a mocked version of the `GeofenceEventHandler` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class GeofenceEventHandlerMock: GeofenceEventHandler, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {}

    public func resetMock() {
        onGeofenceEnteredCallsCount = 0
        onGeofenceEnteredReceivedArguments = nil
        onGeofenceEnteredReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        onGeofenceExitedCallsCount = 0
        onGeofenceExitedReceivedArguments = nil
        onGeofenceExitedReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        onGeofenceDwelledCallsCount = 0
        onGeofenceDwelledReceivedArguments = nil
        onGeofenceDwelledReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - onGeofenceEntered

    /// Number of times the function was called.
    @Atomic private(set) var onGeofenceEnteredCallsCount = 0
    /// `true` if the function was ever called.
    var onGeofenceEnteredCalled: Bool {
        onGeofenceEnteredCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var onGeofenceEnteredReceivedArguments: (region: GeofenceRegion, userLocation: CLLocation?)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var onGeofenceEnteredReceivedInvocations: [(region: GeofenceRegion, userLocation: CLLocation?)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var onGeofenceEnteredClosure: ((GeofenceRegion, CLLocation?) -> Void)?

    /// Mocked function for `onGeofenceEntered(_ region: GeofenceRegion, userLocation: CLLocation?)`. Your opportunity to return a mocked value and check result of mock in test code.
    func onGeofenceEntered(_ region: GeofenceRegion, userLocation: CLLocation?) {
        mockCalled = true
        onGeofenceEnteredCallsCount += 1
        onGeofenceEnteredReceivedArguments = (region: region, userLocation: userLocation)
        onGeofenceEnteredReceivedInvocations.append((region: region, userLocation: userLocation))
        onGeofenceEnteredClosure?(region, userLocation)
    }

    // MARK: - onGeofenceExited

    /// Number of times the function was called.
    @Atomic private(set) var onGeofenceExitedCallsCount = 0
    /// `true` if the function was ever called.
    var onGeofenceExitedCalled: Bool {
        onGeofenceExitedCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var onGeofenceExitedReceivedArguments: (region: GeofenceRegion, userLocation: CLLocation?)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var onGeofenceExitedReceivedInvocations: [(region: GeofenceRegion, userLocation: CLLocation?)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var onGeofenceExitedClosure: ((GeofenceRegion, CLLocation?) -> Void)?

    /// Mocked function for `onGeofenceExited(_ region: GeofenceRegion, userLocation: CLLocation?)`. Your opportunity to return a mocked value and check result of mock in test code.
    func onGeofenceExited(_ region: GeofenceRegion, userLocation: CLLocation?) {
        mockCalled = true
        onGeofenceExitedCallsCount += 1
        onGeofenceExitedReceivedArguments = (region: region, userLocation: userLocation)
        onGeofenceExitedReceivedInvocations.append((region: region, userLocation: userLocation))
        onGeofenceExitedClosure?(region, userLocation)
    }

    // MARK: - onGeofenceDwelled

    /// Number of times the function was called.
    @Atomic private(set) var onGeofenceDwelledCallsCount = 0
    /// `true` if the function was ever called.
    var onGeofenceDwelledCalled: Bool {
        onGeofenceDwelledCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var onGeofenceDwelledReceivedArguments: (region: GeofenceRegion, userLocation: CLLocation?)?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var onGeofenceDwelledReceivedInvocations: [(region: GeofenceRegion, userLocation: CLLocation?)] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var onGeofenceDwelledClosure: ((GeofenceRegion, CLLocation?) -> Void)?

    /// Mocked function for `onGeofenceDwelled(_ region: GeofenceRegion, userLocation: CLLocation?)`. Your opportunity to return a mocked value and check result of mock in test code.
    func onGeofenceDwelled(_ region: GeofenceRegion, userLocation: CLLocation?) {
        mockCalled = true
        onGeofenceDwelledCallsCount += 1
        onGeofenceDwelledReceivedArguments = (region: region, userLocation: userLocation)
        onGeofenceDwelledReceivedInvocations.append((region: region, userLocation: userLocation))
        onGeofenceDwelledClosure?(region, userLocation)
    }
}

/**
 Class to easily create a mocked version of the `GeofenceManaging` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class GeofenceManagingMock: GeofenceManaging, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {}

    public func resetMock() {
        startMonitoringCallsCount = 0
        startMonitoringReceivedArguments = nil
        startMonitoringReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        stopMonitoringCallsCount = 0
        stopMonitoringReceivedArguments = nil
        stopMonitoringReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        stopMonitoringAllCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
        getMonitoredRegionIdsCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
        setEventHandlerCallsCount = 0
        setEventHandlerReceivedArguments = nil
        setEventHandlerReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - startMonitoring

    /// Number of times the function was called.
    @Atomic private(set) var startMonitoringCallsCount = 0
    /// `true` if the function was ever called.
    var startMonitoringCalled: Bool {
        startMonitoringCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var startMonitoringReceivedArguments: GeofenceRegion?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var startMonitoringReceivedInvocations: [GeofenceRegion] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var startMonitoringClosure: ((GeofenceRegion) -> Void)?

    /// Mocked function for `startMonitoring(region: GeofenceRegion)`. Your opportunity to return a mocked value and check result of mock in test code.
    func startMonitoring(region: GeofenceRegion) {
        mockCalled = true
        startMonitoringCallsCount += 1
        startMonitoringReceivedArguments = region
        startMonitoringReceivedInvocations.append(region)
        startMonitoringClosure?(region)
    }

    // MARK: - stopMonitoring

    /// Number of times the function was called.
    @Atomic private(set) var stopMonitoringCallsCount = 0
    /// `true` if the function was ever called.
    var stopMonitoringCalled: Bool {
        stopMonitoringCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var stopMonitoringReceivedArguments: String?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var stopMonitoringReceivedInvocations: [String] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var stopMonitoringClosure: ((String) -> Void)?

    /// Mocked function for `stopMonitoring(regionId: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    func stopMonitoring(regionId: String) {
        mockCalled = true
        stopMonitoringCallsCount += 1
        stopMonitoringReceivedArguments = regionId
        stopMonitoringReceivedInvocations.append(regionId)
        stopMonitoringClosure?(regionId)
    }

    // MARK: - stopMonitoringAll

    /// Number of times the function was called.
    @Atomic private(set) var stopMonitoringAllCallsCount = 0
    /// `true` if the function was ever called.
    var stopMonitoringAllCalled: Bool {
        stopMonitoringAllCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var stopMonitoringAllClosure: (() -> Void)?

    /// Mocked function for `stopMonitoringAll()`. Your opportunity to return a mocked value and check result of mock in test code.
    func stopMonitoringAll() {
        mockCalled = true
        stopMonitoringAllCallsCount += 1
        stopMonitoringAllClosure?()
    }

    // MARK: - getMonitoredRegionIds

    /// Number of times the function was called.
    @Atomic private(set) var getMonitoredRegionIdsCallsCount = 0
    /// `true` if the function was ever called.
    var getMonitoredRegionIdsCalled: Bool {
        getMonitoredRegionIdsCallsCount > 0
    }

    /// Value to return from the mocked function.
    var getMonitoredRegionIdsReturnValue: [String]!
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     The closure has first priority to return a value for the mocked function. If the closure returns `nil`,
     then the mock will attempt to return the value for `getMonitoredRegionIdsReturnValue`
     */
    var getMonitoredRegionIdsClosure: (() -> [String])?

    /// Mocked function for `getMonitoredRegionIds()`. Your opportunity to return a mocked value and check result of mock in test code.
    func getMonitoredRegionIds() -> [String] {
        mockCalled = true
        getMonitoredRegionIdsCallsCount += 1
        return getMonitoredRegionIdsClosure.map { $0() } ?? getMonitoredRegionIdsReturnValue
    }

    // MARK: - setEventHandler

    /// Number of times the function was called.
    @Atomic private(set) var setEventHandlerCallsCount = 0
    /// `true` if the function was ever called.
    var setEventHandlerCalled: Bool {
        setEventHandlerCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var setEventHandlerReceivedArguments: GeofenceEventHandler??
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var setEventHandlerReceivedInvocations: [GeofenceEventHandler?] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var setEventHandlerClosure: ((GeofenceEventHandler?) -> Void)?

    /// Mocked function for `setEventHandler(_ handler: GeofenceEventHandler?)`. Your opportunity to return a mocked value and check result of mock in test code.
    func setEventHandler(_ handler: GeofenceEventHandler?) {
        mockCalled = true
        setEventHandlerCallsCount += 1
        setEventHandlerReceivedArguments = handler
        setEventHandlerReceivedInvocations.append(handler)
        setEventHandlerClosure?(handler)
    }
}

/**
 Class to easily create a mocked version of the `GeofencePreferenceStore` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class GeofencePreferenceStoreMock: GeofencePreferenceStore, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    var mockCalled: Bool = false //

    init() {}

    public func resetMock() {
        saveGeofencesCallsCount = 0
        saveGeofencesReceivedArguments = nil
        saveGeofencesReceivedInvocations = []

        mockCalled = false // do last as resetting properties above can make this true
        loadGeofencesCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
        clearGeofencesCallsCount = 0

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - saveGeofences

    /// Number of times the function was called.
    @Atomic private(set) var saveGeofencesCallsCount = 0
    /// `true` if the function was ever called.
    var saveGeofencesCalled: Bool {
        saveGeofencesCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    @Atomic private(set) var saveGeofencesReceivedArguments: [GeofenceRegion]?
    /// Arguments from *all* of the times that the function was called.
    @Atomic private(set) var saveGeofencesReceivedInvocations: [[GeofenceRegion]] = []
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var saveGeofencesClosure: (([GeofenceRegion]) -> Void)?

    /// Mocked function for `saveGeofences(_ regions: [GeofenceRegion])`. Your opportunity to return a mocked value and check result of mock in test code.
    func saveGeofences(_ regions: [GeofenceRegion]) {
        mockCalled = true
        saveGeofencesCallsCount += 1
        saveGeofencesReceivedArguments = regions
        saveGeofencesReceivedInvocations.append(regions)
        saveGeofencesClosure?(regions)
    }

    // MARK: - loadGeofences

    /// Number of times the function was called.
    @Atomic private(set) var loadGeofencesCallsCount = 0
    /// `true` if the function was ever called.
    var loadGeofencesCalled: Bool {
        loadGeofencesCallsCount > 0
    }

    /// Value to return from the mocked function.
    var loadGeofencesReturnValue: [GeofenceRegion]!
    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     The closure has first priority to return a value for the mocked function. If the closure returns `nil`,
     then the mock will attempt to return the value for `loadGeofencesReturnValue`
     */
    var loadGeofencesClosure: (() -> [GeofenceRegion])?

    /// Mocked function for `loadGeofences()`. Your opportunity to return a mocked value and check result of mock in test code.
    func loadGeofences() -> [GeofenceRegion] {
        mockCalled = true
        loadGeofencesCallsCount += 1
        return loadGeofencesClosure.map { $0() } ?? loadGeofencesReturnValue
    }

    // MARK: - clearGeofences

    /// Number of times the function was called.
    @Atomic private(set) var clearGeofencesCallsCount = 0
    /// `true` if the function was ever called.
    var clearGeofencesCalled: Bool {
        clearGeofencesCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var clearGeofencesClosure: (() -> Void)?

    /// Mocked function for `clearGeofences()`. Your opportunity to return a mocked value and check result of mock in test code.
    func clearGeofences() {
        mockCalled = true
        clearGeofencesCallsCount += 1
        clearGeofencesClosure?()
    }
}

// swiftlint:enable all
