// Generated using Sourcery 2.0.3 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// swiftlint:disable all

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
#if canImport(UserNotifications)
import UserNotifications
#endif
@testable import CioTrackingMigration
@testable import CioInternalCommon

/**
 ######################################################
 Documentation
 ######################################################

 This automatically generated file you are viewing contains mock classes that you can use in your test suite.

 * How do you generate a new mock class?

 1. Mocks are generated from Swift protocols. So, you must make one.

 ```
 protocol FriendsRepository {
     func acceptFriendRequest<Attributes: Encodable>(attributes: Attributes, _ onComplete: @escaping () -> Void)
 }

 class AppFriendsRepository: FriendsRepository {
     ...
 }
 ```

 2. Have your new protocol extend `AutoMockable`:

 ```
 protocol FriendsRepository: AutoMockable {
     func acceptFriendRequest<Attributes: Encodable>(
         // sourcery:Type=Encodable
         attributes: Attributes,
         _ onComplete: @escaping () -> Void)
 }
 ```

 > Notice the use of `// sourcery:Type=Encodable` for the generic type parameter. Without this, the mock would
 fail to compile: `functionNameReceiveArguments = (Attributes)` because `Attributes` is unknown to this `var`.
 Instead, we give the parameter a different type to use for the mock. `Encodable` works in this case.
 It will require a cast in the test function code, however.

 3. Run the command `make generate` on your machine. The new mock should be added to this file.

 * How do you use the mocks in your test class?

 ```
 class ExampleViewModelTest: XCTestCase {
     var viewModel: ExampleViewModel!
     var exampleRepositoryMock: ExampleRepositoryMock!
     override func setUp() {
         exampleRepositoryMock = ExampleRepositoryMock()
         viewModel = AppExampleViewModel(exampleRepository: exampleRepositoryMock)
     }
 }
 ```

 Or, you may need to inject the mock in a different way using the DI.shared graph:

 ```
 class ExampleTest: XCTestCase {
     var exampleViewModelMock: ExampleViewModelMock!
     var example: Example!
     override func setUp() {
         exampleViewModelMock = ExampleViewModelMock()
         DI.shared.override(.exampleViewModel, value: exampleViewModelMock, forType: ExampleViewModel.self)
         example = Example()
     }
 }

 ```

 */

/**
 Class to easily create a mocked version of the `DataPipelineMigrationAction` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
public class DataPipelineMigrationActionMock: @unchecked Sendable, DataPipelineMigrationAction, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    private let _mockCalled: CioInternalCommon.Synchronized<Bool> = .init(false)
    public var mockCalled: Bool {
        get { _mockCalled.wrappedValue }
        set { _mockCalled.wrappedValue = newValue }
    }

    public init() {}

    public func resetMock() {
        _processAlreadyIdentifiedUserCallsCount.wrappedValue = 0
        _processAlreadyIdentifiedUserReceivedArguments.wrappedValue = nil
        _processAlreadyIdentifiedUserReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _processIdentifyFromBGQCallsCount.wrappedValue = 0
        _processIdentifyFromBGQReceivedArguments.wrappedValue = nil
        _processIdentifyFromBGQReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _processScreenEventFromBGQCallsCount.wrappedValue = 0
        _processScreenEventFromBGQReceivedArguments.wrappedValue = nil
        _processScreenEventFromBGQReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _processEventFromBGQCallsCount.wrappedValue = 0
        _processEventFromBGQReceivedArguments.wrappedValue = nil
        _processEventFromBGQReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _processDeleteTokenFromBGQCallsCount.wrappedValue = 0
        _processDeleteTokenFromBGQReceivedArguments.wrappedValue = nil
        _processDeleteTokenFromBGQReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _processRegisterDeviceFromBGQCallsCount.wrappedValue = 0
        _processRegisterDeviceFromBGQReceivedArguments.wrappedValue = nil
        _processRegisterDeviceFromBGQReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _processMetricsFromBGQCallsCount.wrappedValue = 0
        _processMetricsFromBGQReceivedArguments.wrappedValue = nil
        _processMetricsFromBGQReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - processAlreadyIdentifiedUser

    /// Number of times the function was called.
    private let _processAlreadyIdentifiedUserCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var processAlreadyIdentifiedUserCallsCount: Int {
        _processAlreadyIdentifiedUserCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var processAlreadyIdentifiedUserCalled: Bool {
        processAlreadyIdentifiedUserCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _processAlreadyIdentifiedUserReceivedArguments: CioInternalCommon.Synchronized<String?> = .init(nil)
    public var processAlreadyIdentifiedUserReceivedArguments: String? {
        _processAlreadyIdentifiedUserReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _processAlreadyIdentifiedUserReceivedInvocations: CioInternalCommon.Synchronized<[String]> = .init([])
    public var processAlreadyIdentifiedUserReceivedInvocations: [String] {
        _processAlreadyIdentifiedUserReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var processAlreadyIdentifiedUserClosure: ((String) -> Void)?

    /// Mocked function for `processAlreadyIdentifiedUser(identifier: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func processAlreadyIdentifiedUser(identifier: String) {
        mockCalled = true
        _processAlreadyIdentifiedUserCallsCount += 1
        _processAlreadyIdentifiedUserReceivedArguments.wrappedValue = identifier
        _processAlreadyIdentifiedUserReceivedInvocations.append(identifier)
        processAlreadyIdentifiedUserClosure?(identifier)
    }

    // MARK: - processIdentifyFromBGQ

    /// Number of times the function was called.
    private let _processIdentifyFromBGQCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var processIdentifyFromBGQCallsCount: Int {
        _processIdentifyFromBGQCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var processIdentifyFromBGQCalled: Bool {
        processIdentifyFromBGQCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _processIdentifyFromBGQReceivedArguments: CioInternalCommon.Synchronized<(identifier: String, timestamp: String, body: [String: Any]?)?> = .init(nil)
    public var processIdentifyFromBGQReceivedArguments: (identifier: String, timestamp: String, body: [String: Any]?)? {
        _processIdentifyFromBGQReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _processIdentifyFromBGQReceivedInvocations: CioInternalCommon.Synchronized<[(identifier: String, timestamp: String, body: [String: Any]?)]> = .init([])
    public var processIdentifyFromBGQReceivedInvocations: [(identifier: String, timestamp: String, body: [String: Any]?)] {
        _processIdentifyFromBGQReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var processIdentifyFromBGQClosure: ((String, String, [String: Any]?) -> Void)?

    /// Mocked function for `processIdentifyFromBGQ(identifier: String, timestamp: String, body: [String: Any]?)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func processIdentifyFromBGQ(identifier: String, timestamp: String, body: [String: Any]?) {
        mockCalled = true
        _processIdentifyFromBGQCallsCount += 1
        _processIdentifyFromBGQReceivedArguments.wrappedValue = (identifier: identifier, timestamp: timestamp, body: body)
        _processIdentifyFromBGQReceivedInvocations.append((identifier: identifier, timestamp: timestamp, body: body))
        processIdentifyFromBGQClosure?(identifier, timestamp, body)
    }

    // MARK: - processScreenEventFromBGQ

    /// Number of times the function was called.
    private let _processScreenEventFromBGQCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var processScreenEventFromBGQCallsCount: Int {
        _processScreenEventFromBGQCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var processScreenEventFromBGQCalled: Bool {
        processScreenEventFromBGQCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _processScreenEventFromBGQReceivedArguments: CioInternalCommon.Synchronized<(identifier: String, name: String, timestamp: String?, properties: [String: Any])?> = .init(nil)
    public var processScreenEventFromBGQReceivedArguments: (identifier: String, name: String, timestamp: String?, properties: [String: Any])? {
        _processScreenEventFromBGQReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _processScreenEventFromBGQReceivedInvocations: CioInternalCommon.Synchronized<[(identifier: String, name: String, timestamp: String?, properties: [String: Any])]> = .init([])
    public var processScreenEventFromBGQReceivedInvocations: [(identifier: String, name: String, timestamp: String?, properties: [String: Any])] {
        _processScreenEventFromBGQReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var processScreenEventFromBGQClosure: ((String, String, String?, [String: Any]) -> Void)?

    /// Mocked function for `processScreenEventFromBGQ(identifier: String, name: String, timestamp: String?, properties: [String: Any])`. Your opportunity to return a mocked value and check result of mock in test code.
    public func processScreenEventFromBGQ(identifier: String, name: String, timestamp: String?, properties: [String: Any]) {
        mockCalled = true
        _processScreenEventFromBGQCallsCount += 1
        _processScreenEventFromBGQReceivedArguments.wrappedValue = (identifier: identifier, name: name, timestamp: timestamp, properties: properties)
        _processScreenEventFromBGQReceivedInvocations.append((identifier: identifier, name: name, timestamp: timestamp, properties: properties))
        processScreenEventFromBGQClosure?(identifier, name, timestamp, properties)
    }

    // MARK: - processEventFromBGQ

    /// Number of times the function was called.
    private let _processEventFromBGQCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var processEventFromBGQCallsCount: Int {
        _processEventFromBGQCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var processEventFromBGQCalled: Bool {
        processEventFromBGQCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _processEventFromBGQReceivedArguments: CioInternalCommon.Synchronized<(identifier: String, name: String, timestamp: String?, properties: [String: Any])?> = .init(nil)
    public var processEventFromBGQReceivedArguments: (identifier: String, name: String, timestamp: String?, properties: [String: Any])? {
        _processEventFromBGQReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _processEventFromBGQReceivedInvocations: CioInternalCommon.Synchronized<[(identifier: String, name: String, timestamp: String?, properties: [String: Any])]> = .init([])
    public var processEventFromBGQReceivedInvocations: [(identifier: String, name: String, timestamp: String?, properties: [String: Any])] {
        _processEventFromBGQReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var processEventFromBGQClosure: ((String, String, String?, [String: Any]) -> Void)?

    /// Mocked function for `processEventFromBGQ(identifier: String, name: String, timestamp: String?, properties: [String: Any])`. Your opportunity to return a mocked value and check result of mock in test code.
    public func processEventFromBGQ(identifier: String, name: String, timestamp: String?, properties: [String: Any]) {
        mockCalled = true
        _processEventFromBGQCallsCount += 1
        _processEventFromBGQReceivedArguments.wrappedValue = (identifier: identifier, name: name, timestamp: timestamp, properties: properties)
        _processEventFromBGQReceivedInvocations.append((identifier: identifier, name: name, timestamp: timestamp, properties: properties))
        processEventFromBGQClosure?(identifier, name, timestamp, properties)
    }

    // MARK: - processDeleteTokenFromBGQ

    /// Number of times the function was called.
    private let _processDeleteTokenFromBGQCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var processDeleteTokenFromBGQCallsCount: Int {
        _processDeleteTokenFromBGQCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var processDeleteTokenFromBGQCalled: Bool {
        processDeleteTokenFromBGQCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _processDeleteTokenFromBGQReceivedArguments: CioInternalCommon.Synchronized<(identifier: String, token: String, timestamp: String)?> = .init(nil)
    public var processDeleteTokenFromBGQReceivedArguments: (identifier: String, token: String, timestamp: String)? {
        _processDeleteTokenFromBGQReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _processDeleteTokenFromBGQReceivedInvocations: CioInternalCommon.Synchronized<[(identifier: String, token: String, timestamp: String)]> = .init([])
    public var processDeleteTokenFromBGQReceivedInvocations: [(identifier: String, token: String, timestamp: String)] {
        _processDeleteTokenFromBGQReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var processDeleteTokenFromBGQClosure: ((String, String, String) -> Void)?

    /// Mocked function for `processDeleteTokenFromBGQ(identifier: String, token: String, timestamp: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func processDeleteTokenFromBGQ(identifier: String, token: String, timestamp: String) {
        mockCalled = true
        _processDeleteTokenFromBGQCallsCount += 1
        _processDeleteTokenFromBGQReceivedArguments.wrappedValue = (identifier: identifier, token: token, timestamp: timestamp)
        _processDeleteTokenFromBGQReceivedInvocations.append((identifier: identifier, token: token, timestamp: timestamp))
        processDeleteTokenFromBGQClosure?(identifier, token, timestamp)
    }

    // MARK: - processRegisterDeviceFromBGQ

    /// Number of times the function was called.
    private let _processRegisterDeviceFromBGQCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var processRegisterDeviceFromBGQCallsCount: Int {
        _processRegisterDeviceFromBGQCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var processRegisterDeviceFromBGQCalled: Bool {
        processRegisterDeviceFromBGQCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _processRegisterDeviceFromBGQReceivedArguments: CioInternalCommon.Synchronized<(identifier: String, token: String, timestamp: String, attributes: [String: Any]?)?> = .init(nil)
    public var processRegisterDeviceFromBGQReceivedArguments: (identifier: String, token: String, timestamp: String, attributes: [String: Any]?)? {
        _processRegisterDeviceFromBGQReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _processRegisterDeviceFromBGQReceivedInvocations: CioInternalCommon.Synchronized<[(identifier: String, token: String, timestamp: String, attributes: [String: Any]?)]> = .init([])
    public var processRegisterDeviceFromBGQReceivedInvocations: [(identifier: String, token: String, timestamp: String, attributes: [String: Any]?)] {
        _processRegisterDeviceFromBGQReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var processRegisterDeviceFromBGQClosure: ((String, String, String, [String: Any]?) -> Void)?

    /// Mocked function for `processRegisterDeviceFromBGQ(identifier: String, token: String, timestamp: String, attributes: [String: Any]?)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func processRegisterDeviceFromBGQ(identifier: String, token: String, timestamp: String, attributes: [String: Any]?) {
        mockCalled = true
        _processRegisterDeviceFromBGQCallsCount += 1
        _processRegisterDeviceFromBGQReceivedArguments.wrappedValue = (identifier: identifier, token: token, timestamp: timestamp, attributes: attributes)
        _processRegisterDeviceFromBGQReceivedInvocations.append((identifier: identifier, token: token, timestamp: timestamp, attributes: attributes))
        processRegisterDeviceFromBGQClosure?(identifier, token, timestamp, attributes)
    }

    // MARK: - processMetricsFromBGQ

    /// Number of times the function was called.
    private let _processMetricsFromBGQCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var processMetricsFromBGQCallsCount: Int {
        _processMetricsFromBGQCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var processMetricsFromBGQCalled: Bool {
        processMetricsFromBGQCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _processMetricsFromBGQReceivedArguments: CioInternalCommon.Synchronized<(token: String?, event: String, deliveryId: String, timestamp: String, metaData: [String: Any])?> = .init(nil)
    public var processMetricsFromBGQReceivedArguments: (token: String?, event: String, deliveryId: String, timestamp: String, metaData: [String: Any])? {
        _processMetricsFromBGQReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _processMetricsFromBGQReceivedInvocations: CioInternalCommon.Synchronized<[(token: String?, event: String, deliveryId: String, timestamp: String, metaData: [String: Any])]> = .init([])
    public var processMetricsFromBGQReceivedInvocations: [(token: String?, event: String, deliveryId: String, timestamp: String, metaData: [String: Any])] {
        _processMetricsFromBGQReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var processMetricsFromBGQClosure: ((String?, String, String, String, [String: Any]) -> Void)?

    /// Mocked function for `processMetricsFromBGQ(token: String?, event: String, deliveryId: String, timestamp: String, metaData: [String: Any])`. Your opportunity to return a mocked value and check result of mock in test code.
    public func processMetricsFromBGQ(token: String?, event: String, deliveryId: String, timestamp: String, metaData: [String: Any]) {
        mockCalled = true
        _processMetricsFromBGQCallsCount += 1
        _processMetricsFromBGQReceivedArguments.wrappedValue = (token: token, event: event, deliveryId: deliveryId, timestamp: timestamp, metaData: metaData)
        _processMetricsFromBGQReceivedInvocations.append((token: token, event: event, deliveryId: deliveryId, timestamp: timestamp, metaData: metaData))
        processMetricsFromBGQClosure?(token, event, deliveryId, timestamp, metaData)
    }
}

// swiftlint:enable all
