// Generated using Sourcery 2.0.3 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// swiftlint:disable all

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
#if canImport(UserNotifications)
import UserNotifications
#endif
@testable import CioMessagingPush
@testable import CioInternalCommon

/**
 ######################################################
 Documentation
 ######################################################

 This automatically generated file you are viewing contains mock classes that you can use in your test suite.

 * How do you generate a new mock class?

 1. Mocks are generated from Swift protocols. So, you must make one.

 ```
 protocol FriendsRepository {
     func acceptFriendRequest<Attributes: Encodable>(attributes: Attributes, _ onComplete: @escaping () -> Void)
 }

 class AppFriendsRepository: FriendsRepository {
     ...
 }
 ```

 2. Have your new protocol extend `AutoMockable`:

 ```
 protocol FriendsRepository: AutoMockable {
     func acceptFriendRequest<Attributes: Encodable>(
         // sourcery:Type=Encodable
         attributes: Attributes,
         _ onComplete: @escaping () -> Void)
 }
 ```

 > Notice the use of `// sourcery:Type=Encodable` for the generic type parameter. Without this, the mock would
 fail to compile: `functionNameReceiveArguments = (Attributes)` because `Attributes` is unknown to this `var`.
 Instead, we give the parameter a different type to use for the mock. `Encodable` works in this case.
 It will require a cast in the test function code, however.

 3. Run the command `make generate` on your machine. The new mock should be added to this file.

 * How do you use the mocks in your test class?

 ```
 class ExampleViewModelTest: XCTestCase {
     var viewModel: ExampleViewModel!
     var exampleRepositoryMock: ExampleRepositoryMock!
     override func setUp() {
         exampleRepositoryMock = ExampleRepositoryMock()
         viewModel = AppExampleViewModel(exampleRepository: exampleRepositoryMock)
     }
 }
 ```

 Or, you may need to inject the mock in a different way using the DI.shared graph:

 ```
 class ExampleTest: XCTestCase {
     var exampleViewModelMock: ExampleViewModelMock!
     var example: Example!
     override func setUp() {
         exampleViewModelMock = ExampleViewModelMock()
         DI.shared.override(.exampleViewModel, value: exampleViewModelMock, forType: ExampleViewModel.self)
         example = Example()
     }
 }

 ```

 */

/**
 Class to easily create a mocked version of the `MessagingPushInstance` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
public class MessagingPushInstanceMock: @unchecked Sendable, MessagingPushInstance, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    private let _mockCalled: CioInternalCommon.Synchronized<Bool> = .init(false)
    public var mockCalled: Bool {
        get { _mockCalled.wrappedValue }
        set { _mockCalled.wrappedValue = newValue }
    }

    public init() {}

    public func resetMock() {
        _registerDeviceTokenCallsCount.wrappedValue = 0
        _registerDeviceTokenReceivedArguments.wrappedValue = nil
        _registerDeviceTokenReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _deleteDeviceTokenCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _trackMetricCallsCount.wrappedValue = 0
        _trackMetricReceivedArguments.wrappedValue = nil
        _trackMetricReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        #if canImport(UserNotifications)
        _didReceiveNotificationRequestCallsCount.wrappedValue = 0
        _didReceiveNotificationRequestReceivedArguments.wrappedValue = nil
        _didReceiveNotificationRequestReceivedInvocations.wrappedValue = []
        #endif

        mockCalled = false // do last as resetting properties above can make this true
        #if canImport(UserNotifications)
        _serviceExtensionTimeWillExpireCallsCount.wrappedValue = 0
        #endif

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - registerDeviceToken

    /// Number of times the function was called.
    private let _registerDeviceTokenCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var registerDeviceTokenCallsCount: Int {
        _registerDeviceTokenCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var registerDeviceTokenCalled: Bool {
        registerDeviceTokenCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _registerDeviceTokenReceivedArguments: CioInternalCommon.Synchronized<String?> = .init(nil)
    public var registerDeviceTokenReceivedArguments: String? {
        _registerDeviceTokenReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _registerDeviceTokenReceivedInvocations: CioInternalCommon.Synchronized<[String]> = .init([])
    public var registerDeviceTokenReceivedInvocations: [String] {
        _registerDeviceTokenReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var registerDeviceTokenClosure: ((String) -> Void)?

    /// Mocked function for `registerDeviceToken(_ deviceToken: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func registerDeviceToken(_ deviceToken: String) {
        mockCalled = true
        _registerDeviceTokenCallsCount += 1
        _registerDeviceTokenReceivedArguments.wrappedValue = deviceToken
        _registerDeviceTokenReceivedInvocations.append(deviceToken)
        registerDeviceTokenClosure?(deviceToken)
    }

    // MARK: - deleteDeviceToken

    /// Number of times the function was called.
    private let _deleteDeviceTokenCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var deleteDeviceTokenCallsCount: Int {
        _deleteDeviceTokenCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var deleteDeviceTokenCalled: Bool {
        deleteDeviceTokenCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var deleteDeviceTokenClosure: (() -> Void)?

    /// Mocked function for `deleteDeviceToken()`. Your opportunity to return a mocked value and check result of mock in test code.
    public func deleteDeviceToken() {
        mockCalled = true
        _deleteDeviceTokenCallsCount += 1
        deleteDeviceTokenClosure?()
    }

    // MARK: - trackMetric

    /// Number of times the function was called.
    private let _trackMetricCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var trackMetricCallsCount: Int {
        _trackMetricCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var trackMetricCalled: Bool {
        trackMetricCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _trackMetricReceivedArguments: CioInternalCommon.Synchronized<(deliveryID: String, event: Metric, deviceToken: String)?> = .init(nil)
    public var trackMetricReceivedArguments: (deliveryID: String, event: Metric, deviceToken: String)? {
        _trackMetricReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _trackMetricReceivedInvocations: CioInternalCommon.Synchronized<[(deliveryID: String, event: Metric, deviceToken: String)]> = .init([])
    public var trackMetricReceivedInvocations: [(deliveryID: String, event: Metric, deviceToken: String)] {
        _trackMetricReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var trackMetricClosure: ((String, Metric, String) -> Void)?

    /// Mocked function for `trackMetric(deliveryID: String, event: Metric, deviceToken: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    public func trackMetric(deliveryID: String, event: Metric, deviceToken: String) {
        mockCalled = true
        _trackMetricCallsCount += 1
        _trackMetricReceivedArguments.wrappedValue = (deliveryID: deliveryID, event: event, deviceToken: deviceToken)
        _trackMetricReceivedInvocations.append((deliveryID: deliveryID, event: event, deviceToken: deviceToken))
        trackMetricClosure?(deliveryID, event, deviceToken)
    }

    // MARK: - didReceive

    #if canImport(UserNotifications)
    /// Number of times the function was called.
    private let _didReceiveNotificationRequestCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var didReceiveNotificationRequestCallsCount: Int {
        _didReceiveNotificationRequestCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var didReceiveNotificationRequestCalled: Bool {
        didReceiveNotificationRequestCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _didReceiveNotificationRequestReceivedArguments: CioInternalCommon.Synchronized<(request: UNNotificationRequest, contentHandler: (UNNotificationContent) -> Void)?> = .init(nil)
    public var didReceiveNotificationRequestReceivedArguments: (request: UNNotificationRequest, contentHandler: (UNNotificationContent) -> Void)? {
        _didReceiveNotificationRequestReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _didReceiveNotificationRequestReceivedInvocations: CioInternalCommon.Synchronized<[(request: UNNotificationRequest, contentHandler: (UNNotificationContent) -> Void)]> = .init([])
    public var didReceiveNotificationRequestReceivedInvocations: [(request: UNNotificationRequest, contentHandler: (UNNotificationContent) -> Void)] {
        _didReceiveNotificationRequestReceivedInvocations.wrappedValue
    }

    /// Value to return from the mocked function.
    private let _didReceiveNotificationRequestReturnValue: CioInternalCommon.Synchronized<Bool?> = .init(nil)
    public var didReceiveNotificationRequestReturnValue: Bool! {
        get { _didReceiveNotificationRequestReturnValue.wrappedValue }
        set { _didReceiveNotificationRequestReturnValue.wrappedValue = newValue }
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     The closure has first priority to return a value for the mocked function. If the closure returns `nil`,
     then the mock will attempt to return the value for `didReceiveNotificationRequestReturnValue`
     */
    public var didReceiveNotificationRequestClosure: ((UNNotificationRequest, @escaping (UNNotificationContent) -> Void) -> Bool)?

    /// Mocked function for `didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void)`. Your opportunity to return a mocked value and check result of mock in test code.
    @discardableResult
    public func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) -> Bool {
        mockCalled = true
        _didReceiveNotificationRequestCallsCount += 1
        _didReceiveNotificationRequestReceivedArguments.wrappedValue = (request: request, contentHandler: contentHandler)
        _didReceiveNotificationRequestReceivedInvocations.append((request: request, contentHandler: contentHandler))
        return didReceiveNotificationRequestClosure.map { $0(request, contentHandler) } ?? didReceiveNotificationRequestReturnValue
    }
    #endif

    // MARK: - serviceExtensionTimeWillExpire

    #if canImport(UserNotifications)
    /// Number of times the function was called.
    private let _serviceExtensionTimeWillExpireCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var serviceExtensionTimeWillExpireCallsCount: Int {
        _serviceExtensionTimeWillExpireCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    public var serviceExtensionTimeWillExpireCalled: Bool {
        serviceExtensionTimeWillExpireCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    public var serviceExtensionTimeWillExpireClosure: (() -> Void)?

    /// Mocked function for `serviceExtensionTimeWillExpire()`. Your opportunity to return a mocked value and check result of mock in test code.
    public func serviceExtensionTimeWillExpire() {
        mockCalled = true
        _serviceExtensionTimeWillExpireCallsCount += 1
        serviceExtensionTimeWillExpireClosure?()
    }
    #endif
}

/**
 Class to easily create a mocked version of the `PushClickHandler` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
@available(iOSApplicationExtension, unavailable)
class PushClickHandlerMock: @unchecked Sendable, PushClickHandler, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    private let _mockCalled: CioInternalCommon.Synchronized<Bool> = .init(false)
    var mockCalled: Bool {
        get { _mockCalled.wrappedValue }
        set { _mockCalled.wrappedValue = newValue }
    }

    init() {}

    public func resetMock() {
        _cleanupAfterPushInteractedWithCallsCount.wrappedValue = 0
        _cleanupAfterPushInteractedWithReceivedArguments.wrappedValue = nil
        _cleanupAfterPushInteractedWithReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _trackPushMetricsCallsCount.wrappedValue = 0
        _trackPushMetricsReceivedArguments.wrappedValue = nil
        _trackPushMetricsReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _handleDeepLinkCallsCount.wrappedValue = 0
        _handleDeepLinkReceivedArguments.wrappedValue = nil
        _handleDeepLinkReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - cleanupAfterPushInteractedWith

    /// Number of times the function was called.
    private let _cleanupAfterPushInteractedWithCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var cleanupAfterPushInteractedWithCallsCount: Int {
        _cleanupAfterPushInteractedWithCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var cleanupAfterPushInteractedWithCalled: Bool {
        cleanupAfterPushInteractedWithCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _cleanupAfterPushInteractedWithReceivedArguments: CioInternalCommon.Synchronized<PushNotification?> = .init(nil)
    var cleanupAfterPushInteractedWithReceivedArguments: PushNotification? {
        _cleanupAfterPushInteractedWithReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _cleanupAfterPushInteractedWithReceivedInvocations: CioInternalCommon.Synchronized<[PushNotification]> = .init([])
    var cleanupAfterPushInteractedWithReceivedInvocations: [PushNotification] {
        _cleanupAfterPushInteractedWithReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var cleanupAfterPushInteractedWithClosure: ((PushNotification) -> Void)?

    /// Mocked function for `cleanupAfterPushInteractedWith(for push: PushNotification)`. Your opportunity to return a mocked value and check result of mock in test code.
    func cleanupAfterPushInteractedWith(for push: PushNotification) {
        mockCalled = true
        _cleanupAfterPushInteractedWithCallsCount += 1
        _cleanupAfterPushInteractedWithReceivedArguments.wrappedValue = push
        _cleanupAfterPushInteractedWithReceivedInvocations.append(push)
        cleanupAfterPushInteractedWithClosure?(push)
    }

    // MARK: - trackPushMetrics

    /// Number of times the function was called.
    private let _trackPushMetricsCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var trackPushMetricsCallsCount: Int {
        _trackPushMetricsCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var trackPushMetricsCalled: Bool {
        trackPushMetricsCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _trackPushMetricsReceivedArguments: CioInternalCommon.Synchronized<PushNotification?> = .init(nil)
    var trackPushMetricsReceivedArguments: PushNotification? {
        _trackPushMetricsReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _trackPushMetricsReceivedInvocations: CioInternalCommon.Synchronized<[PushNotification]> = .init([])
    var trackPushMetricsReceivedInvocations: [PushNotification] {
        _trackPushMetricsReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var trackPushMetricsClosure: ((PushNotification) -> Void)?

    /// Mocked function for `trackPushMetrics(for push: PushNotification)`. Your opportunity to return a mocked value and check result of mock in test code.
    func trackPushMetrics(for push: PushNotification) {
        mockCalled = true
        _trackPushMetricsCallsCount += 1
        _trackPushMetricsReceivedArguments.wrappedValue = push
        _trackPushMetricsReceivedInvocations.append(push)
        trackPushMetricsClosure?(push)
    }

    // MARK: - handleDeepLink

    /// Number of times the function was called.
    private let _handleDeepLinkCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var handleDeepLinkCallsCount: Int {
        _handleDeepLinkCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var handleDeepLinkCalled: Bool {
        handleDeepLinkCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _handleDeepLinkReceivedArguments: CioInternalCommon.Synchronized<PushNotification?> = .init(nil)
    var handleDeepLinkReceivedArguments: PushNotification? {
        _handleDeepLinkReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _handleDeepLinkReceivedInvocations: CioInternalCommon.Synchronized<[PushNotification]> = .init([])
    var handleDeepLinkReceivedInvocations: [PushNotification] {
        _handleDeepLinkReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var handleDeepLinkClosure: ((PushNotification) -> Void)?

    /// Mocked function for `handleDeepLink(for push: PushNotification)`. Your opportunity to return a mocked value and check result of mock in test code.
    func handleDeepLink(for push: PushNotification) {
        mockCalled = true
        _handleDeepLinkCallsCount += 1
        _handleDeepLinkReceivedArguments.wrappedValue = push
        _handleDeepLinkReceivedInvocations.append(push)
        handleDeepLinkClosure?(push)
    }
}

/**
 Class to easily create a mocked version of the `PushNotificationLogger` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class PushNotificationLoggerMock: @unchecked Sendable, PushNotificationLogger, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    private let _mockCalled: CioInternalCommon.Synchronized<Bool> = .init(false)
    var mockCalled: Bool {
        get { _mockCalled.wrappedValue }
        set { _mockCalled.wrappedValue = newValue }
    }

    init() {}

    public func resetMock() {
        _logReceivedPushMessageCallsCount.wrappedValue = 0
        _logReceivedPushMessageReceivedArguments.wrappedValue = nil
        _logReceivedPushMessageReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _logReceivedCioPushMessageCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _logReceivedNonCioPushMessageCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _logReceivedPushMessageWithEmptyDeliveryIdCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _logTrackingPushMessageDeliveredCallsCount.wrappedValue = 0
        _logTrackingPushMessageDeliveredReceivedArguments.wrappedValue = nil
        _logTrackingPushMessageDeliveredReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _logPushMetricsAutoTrackingDisabledCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _logPushMetricTrackedCallsCount.wrappedValue = 0
        _logPushMetricTrackedReceivedArguments.wrappedValue = nil
        _logPushMetricTrackedReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _logPushMetricTrackingFailedCallsCount.wrappedValue = 0
        _logPushMetricTrackingFailedReceivedArguments.wrappedValue = nil
        _logPushMetricTrackingFailedReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _logClickedPushMessageCallsCount.wrappedValue = 0
        _logClickedPushMessageReceivedArguments.wrappedValue = nil
        _logClickedPushMessageReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
        _logClickedCioPushMessageCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _logClickedNonCioPushMessageCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _logClickedPushMessageWithEmptyDeliveryIdCallsCount.wrappedValue = 0

        mockCalled = false // do last as resetting properties above can make this true
        _logTrackingPushMessageOpenedCallsCount.wrappedValue = 0
        _logTrackingPushMessageOpenedReceivedArguments.wrappedValue = nil
        _logTrackingPushMessageOpenedReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - logReceivedPushMessage

    /// Number of times the function was called.
    private let _logReceivedPushMessageCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logReceivedPushMessageCallsCount: Int {
        _logReceivedPushMessageCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logReceivedPushMessageCalled: Bool {
        logReceivedPushMessageCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _logReceivedPushMessageReceivedArguments: CioInternalCommon.Synchronized<PushNotification?> = .init(nil)
    var logReceivedPushMessageReceivedArguments: PushNotification? {
        _logReceivedPushMessageReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _logReceivedPushMessageReceivedInvocations: CioInternalCommon.Synchronized<[PushNotification]> = .init([])
    var logReceivedPushMessageReceivedInvocations: [PushNotification] {
        _logReceivedPushMessageReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logReceivedPushMessageClosure: ((PushNotification) -> Void)?

    /// Mocked function for `logReceivedPushMessage(notification: PushNotification)`. Your opportunity to return a mocked value and check result of mock in test code.
    func logReceivedPushMessage(notification: PushNotification) {
        mockCalled = true
        _logReceivedPushMessageCallsCount += 1
        _logReceivedPushMessageReceivedArguments.wrappedValue = notification
        _logReceivedPushMessageReceivedInvocations.append(notification)
        logReceivedPushMessageClosure?(notification)
    }

    // MARK: - logReceivedCioPushMessage

    /// Number of times the function was called.
    private let _logReceivedCioPushMessageCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logReceivedCioPushMessageCallsCount: Int {
        _logReceivedCioPushMessageCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logReceivedCioPushMessageCalled: Bool {
        logReceivedCioPushMessageCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logReceivedCioPushMessageClosure: (() -> Void)?

    /// Mocked function for `logReceivedCioPushMessage()`. Your opportunity to return a mocked value and check result of mock in test code.
    func logReceivedCioPushMessage() {
        mockCalled = true
        _logReceivedCioPushMessageCallsCount += 1
        logReceivedCioPushMessageClosure?()
    }

    // MARK: - logReceivedNonCioPushMessage

    /// Number of times the function was called.
    private let _logReceivedNonCioPushMessageCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logReceivedNonCioPushMessageCallsCount: Int {
        _logReceivedNonCioPushMessageCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logReceivedNonCioPushMessageCalled: Bool {
        logReceivedNonCioPushMessageCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logReceivedNonCioPushMessageClosure: (() -> Void)?

    /// Mocked function for `logReceivedNonCioPushMessage()`. Your opportunity to return a mocked value and check result of mock in test code.
    func logReceivedNonCioPushMessage() {
        mockCalled = true
        _logReceivedNonCioPushMessageCallsCount += 1
        logReceivedNonCioPushMessageClosure?()
    }

    // MARK: - logReceivedPushMessageWithEmptyDeliveryId

    /// Number of times the function was called.
    private let _logReceivedPushMessageWithEmptyDeliveryIdCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logReceivedPushMessageWithEmptyDeliveryIdCallsCount: Int {
        _logReceivedPushMessageWithEmptyDeliveryIdCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logReceivedPushMessageWithEmptyDeliveryIdCalled: Bool {
        logReceivedPushMessageWithEmptyDeliveryIdCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logReceivedPushMessageWithEmptyDeliveryIdClosure: (() -> Void)?

    /// Mocked function for `logReceivedPushMessageWithEmptyDeliveryId()`. Your opportunity to return a mocked value and check result of mock in test code.
    func logReceivedPushMessageWithEmptyDeliveryId() {
        mockCalled = true
        _logReceivedPushMessageWithEmptyDeliveryIdCallsCount += 1
        logReceivedPushMessageWithEmptyDeliveryIdClosure?()
    }

    // MARK: - logTrackingPushMessageDelivered

    /// Number of times the function was called.
    private let _logTrackingPushMessageDeliveredCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logTrackingPushMessageDeliveredCallsCount: Int {
        _logTrackingPushMessageDeliveredCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logTrackingPushMessageDeliveredCalled: Bool {
        logTrackingPushMessageDeliveredCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _logTrackingPushMessageDeliveredReceivedArguments: CioInternalCommon.Synchronized<String?> = .init(nil)
    var logTrackingPushMessageDeliveredReceivedArguments: String? {
        _logTrackingPushMessageDeliveredReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _logTrackingPushMessageDeliveredReceivedInvocations: CioInternalCommon.Synchronized<[String]> = .init([])
    var logTrackingPushMessageDeliveredReceivedInvocations: [String] {
        _logTrackingPushMessageDeliveredReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logTrackingPushMessageDeliveredClosure: ((String) -> Void)?

    /// Mocked function for `logTrackingPushMessageDelivered(deliveryId: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    func logTrackingPushMessageDelivered(deliveryId: String) {
        mockCalled = true
        _logTrackingPushMessageDeliveredCallsCount += 1
        _logTrackingPushMessageDeliveredReceivedArguments.wrappedValue = deliveryId
        _logTrackingPushMessageDeliveredReceivedInvocations.append(deliveryId)
        logTrackingPushMessageDeliveredClosure?(deliveryId)
    }

    // MARK: - logPushMetricsAutoTrackingDisabled

    /// Number of times the function was called.
    private let _logPushMetricsAutoTrackingDisabledCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logPushMetricsAutoTrackingDisabledCallsCount: Int {
        _logPushMetricsAutoTrackingDisabledCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logPushMetricsAutoTrackingDisabledCalled: Bool {
        logPushMetricsAutoTrackingDisabledCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logPushMetricsAutoTrackingDisabledClosure: (() -> Void)?

    /// Mocked function for `logPushMetricsAutoTrackingDisabled()`. Your opportunity to return a mocked value and check result of mock in test code.
    func logPushMetricsAutoTrackingDisabled() {
        mockCalled = true
        _logPushMetricsAutoTrackingDisabledCallsCount += 1
        logPushMetricsAutoTrackingDisabledClosure?()
    }

    // MARK: - logPushMetricTracked

    /// Number of times the function was called.
    private let _logPushMetricTrackedCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logPushMetricTrackedCallsCount: Int {
        _logPushMetricTrackedCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logPushMetricTrackedCalled: Bool {
        logPushMetricTrackedCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _logPushMetricTrackedReceivedArguments: CioInternalCommon.Synchronized<(deliveryId: String, event: String)?> = .init(nil)
    var logPushMetricTrackedReceivedArguments: (deliveryId: String, event: String)? {
        _logPushMetricTrackedReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _logPushMetricTrackedReceivedInvocations: CioInternalCommon.Synchronized<[(deliveryId: String, event: String)]> = .init([])
    var logPushMetricTrackedReceivedInvocations: [(deliveryId: String, event: String)] {
        _logPushMetricTrackedReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logPushMetricTrackedClosure: ((String, String) -> Void)?

    /// Mocked function for `logPushMetricTracked(deliveryId: String, event: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    func logPushMetricTracked(deliveryId: String, event: String) {
        mockCalled = true
        _logPushMetricTrackedCallsCount += 1
        _logPushMetricTrackedReceivedArguments.wrappedValue = (deliveryId: deliveryId, event: event)
        _logPushMetricTrackedReceivedInvocations.append((deliveryId: deliveryId, event: event))
        logPushMetricTrackedClosure?(deliveryId, event)
    }

    // MARK: - logPushMetricTrackingFailed

    /// Number of times the function was called.
    private let _logPushMetricTrackingFailedCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logPushMetricTrackingFailedCallsCount: Int {
        _logPushMetricTrackingFailedCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logPushMetricTrackingFailedCalled: Bool {
        logPushMetricTrackingFailedCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _logPushMetricTrackingFailedReceivedArguments: CioInternalCommon.Synchronized<(deliveryId: String, event: String, error: Error)?> = .init(nil)
    var logPushMetricTrackingFailedReceivedArguments: (deliveryId: String, event: String, error: Error)? {
        _logPushMetricTrackingFailedReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _logPushMetricTrackingFailedReceivedInvocations: CioInternalCommon.Synchronized<[(deliveryId: String, event: String, error: Error)]> = .init([])
    var logPushMetricTrackingFailedReceivedInvocations: [(deliveryId: String, event: String, error: Error)] {
        _logPushMetricTrackingFailedReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logPushMetricTrackingFailedClosure: ((String, String, Error) -> Void)?

    /// Mocked function for `logPushMetricTrackingFailed(deliveryId: String, event: String, error: Error)`. Your opportunity to return a mocked value and check result of mock in test code.
    func logPushMetricTrackingFailed(deliveryId: String, event: String, error: Error) {
        mockCalled = true
        _logPushMetricTrackingFailedCallsCount += 1
        _logPushMetricTrackingFailedReceivedArguments.wrappedValue = (deliveryId: deliveryId, event: event, error: error)
        _logPushMetricTrackingFailedReceivedInvocations.append((deliveryId: deliveryId, event: event, error: error))
        logPushMetricTrackingFailedClosure?(deliveryId, event, error)
    }

    // MARK: - logClickedPushMessage

    /// Number of times the function was called.
    private let _logClickedPushMessageCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logClickedPushMessageCallsCount: Int {
        _logClickedPushMessageCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logClickedPushMessageCalled: Bool {
        logClickedPushMessageCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _logClickedPushMessageReceivedArguments: CioInternalCommon.Synchronized<PushNotification?> = .init(nil)
    var logClickedPushMessageReceivedArguments: PushNotification? {
        _logClickedPushMessageReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _logClickedPushMessageReceivedInvocations: CioInternalCommon.Synchronized<[PushNotification]> = .init([])
    var logClickedPushMessageReceivedInvocations: [PushNotification] {
        _logClickedPushMessageReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logClickedPushMessageClosure: ((PushNotification) -> Void)?

    /// Mocked function for `logClickedPushMessage(notification: PushNotification)`. Your opportunity to return a mocked value and check result of mock in test code.
    func logClickedPushMessage(notification: PushNotification) {
        mockCalled = true
        _logClickedPushMessageCallsCount += 1
        _logClickedPushMessageReceivedArguments.wrappedValue = notification
        _logClickedPushMessageReceivedInvocations.append(notification)
        logClickedPushMessageClosure?(notification)
    }

    // MARK: - logClickedCioPushMessage

    /// Number of times the function was called.
    private let _logClickedCioPushMessageCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logClickedCioPushMessageCallsCount: Int {
        _logClickedCioPushMessageCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logClickedCioPushMessageCalled: Bool {
        logClickedCioPushMessageCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logClickedCioPushMessageClosure: (() -> Void)?

    /// Mocked function for `logClickedCioPushMessage()`. Your opportunity to return a mocked value and check result of mock in test code.
    func logClickedCioPushMessage() {
        mockCalled = true
        _logClickedCioPushMessageCallsCount += 1
        logClickedCioPushMessageClosure?()
    }

    // MARK: - logClickedNonCioPushMessage

    /// Number of times the function was called.
    private let _logClickedNonCioPushMessageCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logClickedNonCioPushMessageCallsCount: Int {
        _logClickedNonCioPushMessageCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logClickedNonCioPushMessageCalled: Bool {
        logClickedNonCioPushMessageCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logClickedNonCioPushMessageClosure: (() -> Void)?

    /// Mocked function for `logClickedNonCioPushMessage()`. Your opportunity to return a mocked value and check result of mock in test code.
    func logClickedNonCioPushMessage() {
        mockCalled = true
        _logClickedNonCioPushMessageCallsCount += 1
        logClickedNonCioPushMessageClosure?()
    }

    // MARK: - logClickedPushMessageWithEmptyDeliveryId

    /// Number of times the function was called.
    private let _logClickedPushMessageWithEmptyDeliveryIdCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logClickedPushMessageWithEmptyDeliveryIdCallsCount: Int {
        _logClickedPushMessageWithEmptyDeliveryIdCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logClickedPushMessageWithEmptyDeliveryIdCalled: Bool {
        logClickedPushMessageWithEmptyDeliveryIdCallsCount > 0
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logClickedPushMessageWithEmptyDeliveryIdClosure: (() -> Void)?

    /// Mocked function for `logClickedPushMessageWithEmptyDeliveryId()`. Your opportunity to return a mocked value and check result of mock in test code.
    func logClickedPushMessageWithEmptyDeliveryId() {
        mockCalled = true
        _logClickedPushMessageWithEmptyDeliveryIdCallsCount += 1
        logClickedPushMessageWithEmptyDeliveryIdClosure?()
    }

    // MARK: - logTrackingPushMessageOpened

    /// Number of times the function was called.
    private let _logTrackingPushMessageOpenedCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var logTrackingPushMessageOpenedCallsCount: Int {
        _logTrackingPushMessageOpenedCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var logTrackingPushMessageOpenedCalled: Bool {
        logTrackingPushMessageOpenedCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _logTrackingPushMessageOpenedReceivedArguments: CioInternalCommon.Synchronized<String?> = .init(nil)
    var logTrackingPushMessageOpenedReceivedArguments: String? {
        _logTrackingPushMessageOpenedReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _logTrackingPushMessageOpenedReceivedInvocations: CioInternalCommon.Synchronized<[String]> = .init([])
    var logTrackingPushMessageOpenedReceivedInvocations: [String] {
        _logTrackingPushMessageOpenedReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var logTrackingPushMessageOpenedClosure: ((String) -> Void)?

    /// Mocked function for `logTrackingPushMessageOpened(deliveryId: String)`. Your opportunity to return a mocked value and check result of mock in test code.
    func logTrackingPushMessageOpened(deliveryId: String) {
        mockCalled = true
        _logTrackingPushMessageOpenedCallsCount += 1
        _logTrackingPushMessageOpenedReceivedArguments.wrappedValue = deliveryId
        _logTrackingPushMessageOpenedReceivedInvocations.append(deliveryId)
        logTrackingPushMessageOpenedClosure?(deliveryId)
    }
}

/**
 Class to easily create a mocked version of the `RichPushDeliveryTracker` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
class RichPushDeliveryTrackerMock: @unchecked Sendable, RichPushDeliveryTracker, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    private let _mockCalled: CioInternalCommon.Synchronized<Bool> = .init(false)
    var mockCalled: Bool {
        get { _mockCalled.wrappedValue }
        set { _mockCalled.wrappedValue = newValue }
    }

    init() {}

    public func resetMock() {
        _trackMetricCallsCount.wrappedValue = 0
        _trackMetricReceivedArguments.wrappedValue = nil
        _trackMetricReceivedInvocations.wrappedValue = []

        mockCalled = false // do last as resetting properties above can make this true
    }

    // MARK: - trackMetric

    /// Number of times the function was called.
    private let _trackMetricCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    var trackMetricCallsCount: Int {
        _trackMetricCallsCount.wrappedValue
    }

    /// `true` if the function was ever called.
    var trackMetricCalled: Bool {
        trackMetricCallsCount > 0
    }

    /// The arguments from the *last* time the function was called.
    private let _trackMetricReceivedArguments: CioInternalCommon.Synchronized<(token: String, event: Metric, deliveryId: String, timestamp: String?, onComplete: (Result<Void, HttpRequestError>) -> Void)?> = .init(nil)
    var trackMetricReceivedArguments: (token: String, event: Metric, deliveryId: String, timestamp: String?, onComplete: (Result<Void, HttpRequestError>) -> Void)? {
        _trackMetricReceivedArguments.wrappedValue
    }

    /// Arguments from *all* of the times that the function was called.
    private let _trackMetricReceivedInvocations: CioInternalCommon.Synchronized<[(token: String, event: Metric, deliveryId: String, timestamp: String?, onComplete: (Result<Void, HttpRequestError>) -> Void)]> = .init([])
    var trackMetricReceivedInvocations: [(token: String, event: Metric, deliveryId: String, timestamp: String?, onComplete: (Result<Void, HttpRequestError>) -> Void)] {
        _trackMetricReceivedInvocations.wrappedValue
    }

    /**
     Set closure to get called when function gets called. Great way to test logic or return a value for the function.
     */
    var trackMetricClosure: ((String, Metric, String, String?, @escaping (Result<Void, HttpRequestError>) -> Void) -> Void)?

    /// Mocked function for `trackMetric(token: String, event: Metric, deliveryId: String, timestamp: String?, onComplete: @escaping (Result<Void, HttpRequestError>) -> Void)`. Your opportunity to return a mocked value and check result of mock in test code.
    func trackMetric(token: String, event: Metric, deliveryId: String, timestamp: String?, onComplete: @escaping (Result<Void, HttpRequestError>) -> Void) {
        mockCalled = true
        _trackMetricCallsCount += 1
        _trackMetricReceivedArguments.wrappedValue = (token: token, event: event, deliveryId: deliveryId, timestamp: timestamp, onComplete: onComplete)
        _trackMetricReceivedInvocations.append((token: token, event: event, deliveryId: deliveryId, timestamp: timestamp, onComplete: onComplete))
        trackMetricClosure?(token, event, deliveryId, timestamp, onComplete)
    }
}

/**
 Class to easily create a mocked version of the `UserNotificationCenterIntegration` class.
 This class is equipped with functions and properties ready for you to mock!

 Note: This file is automatically generated. This means the mocks should always be up-to-date and has a consistent API.
 See the SDK documentation to learn the basics behind using the mock classes in the SDK.
 */
public class UserNotificationCenterIntegrationMock: @unchecked Sendable, UserNotificationCenterIntegration, Mock {
    /// If *any* interactions done on mock. `true` if any method or property getter/setter called.
    private let _mockCalled: CioInternalCommon.Synchronized<Bool> = .init(false)
    public var mockCalled: Bool {
        get { _mockCalled.wrappedValue }
        set { _mockCalled.wrappedValue = newValue }
    }

    public init() {}

    /**
     When setter of the property called, the value given to setter is set here.
     When the getter of the property called, the value set here will be returned. Your chance to mock the property.
     */
    private let _underlyingDelegate: CioInternalCommon.Synchronized<UNUserNotificationCenterDelegate?> = .init(nil)
    public var underlyingDelegate: UNUserNotificationCenterDelegate? {
        get { _underlyingDelegate.wrappedValue }
        set { _underlyingDelegate.wrappedValue = newValue }
    }

    /// `true` if the getter or setter of property is called at least once.
    public var delegateCalled: Bool {
        delegateGetCalled || delegateSetCalled
    }

    /// `true` if the getter called on the property at least once.
    public var delegateGetCalled: Bool {
        delegateGetCallsCount > 0
    }

    private let _delegateGetCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var delegateGetCallsCount: Int {
        _delegateGetCallsCount.wrappedValue
    }

    /// `true` if the setter called on the property at least once.
    public var delegateSetCalled: Bool {
        delegateSetCallsCount > 0
    }

    private let _delegateSetCallsCount: CioInternalCommon.Synchronized<Int> = .init(0)
    public var delegateSetCallsCount: Int {
        _delegateSetCallsCount.wrappedValue
    }

    /// The mocked property with a getter and setter.
    public var delegate: UNUserNotificationCenterDelegate? {
        get {
            mockCalled = true
            _delegateGetCallsCount += 1
            return underlyingDelegate
        }
        set(value) {
            mockCalled = true
            _delegateSetCallsCount += 1
            underlyingDelegate = value
        }
    }

    public func resetMock() {
        delegate = nil
        _delegateGetCallsCount.wrappedValue = 0
        _delegateSetCallsCount.wrappedValue = 0
    }
}

// swiftlint:enable all
