minimum_ios_version = '13.0'

platform :ios, minimum_ios_version
use_frameworks!

# Always install the SDK from the local source code so the sample app tests this specific commit of the code. 
sdk_local_path = File.join(File.dirname(__FILE__), '../../')

target 'test cocoapods' do
  pod 'CustomerIOCommon', :path => sdk_local_path
  pod 'CustomerIOMessagingPush', :path => sdk_local_path
  pod 'CustomerIOMessagingPushFCM', :path => sdk_local_path
  pod 'CustomerIOMessagingInApp', :path => sdk_local_path

  pod 'FirebaseMessaging', '~> 10.6'
end

target 'Rich Push Notification Service Extension' do 
  pod 'CustomerIOCommon', :path => sdk_local_path
  pod 'CustomerIOMessagingPush', :path => sdk_local_path
  pod 'CustomerIOMessagingPushFCM', :path => sdk_local_path
end 

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_ios_version
    end
  end
end