platform :ios, '13.0'
use_frameworks!

# Always install the SDK from the local source code so the sample app tests this specific commit of the code. 
sdk_local_path = File.join(File.dirname(__FILE__), '../../')

target 'test cocoapods' do
  pod 'CustomerIOCommon', :path => sdk_local_path
  pod 'CustomerIOTracking', :path => sdk_local_path
  pod 'CustomerIOMessagingPush', :path => sdk_local_path    
  pod 'CustomerIOMessagingInApp', :path => sdk_local_path
  pod 'CustomerIOMessagingPushFCM', :path => sdk_local_path

  # The "CustomerIOMessagingPushFCM" SDK installs the FCM SDK for you, defaulting to the latest version. 
  # If your app needs to use a specific version of the FCM SDK, you can add the line below to your app's Podfile 
  # and the version you specify will override the version in the "CustomerIOMessagingPushFCM" SDK. 
  # 
  # pod 'FirebaseMessaging', '~> 10.6'
  # 
  # See docs to learn the Podfile syntax for specifying version numbers:
  # https://guides.cocoapods.org/syntax/podfile.html#pod

  pod 'SampleAppsCommon', :path => File.join(File.dirname(__FILE__), '../Common')
end

target 'Rich Push Notification Service Extension' do 
  pod 'CustomerIOCommon', :path => sdk_local_path
  pod 'CustomerIOTracking', :path => sdk_local_path
  pod 'CustomerIOMessagingPush', :path => sdk_local_path
  pod 'CustomerIOMessagingPushFCM', :path => sdk_local_path
end 
