platform :ios, '13.0'
use_frameworks!

# Always install the SDK from the local source code so the sample app tests this specific commit of the code. 
sdk_local_path = File.join(File.dirname(__FILE__), '../../')

target 'test cocoapods' do
  pod 'CustomerIOCommon', :path => sdk_local_path
  pod 'CustomerIOTracking', :path => sdk_local_path
  pod 'CustomerIOMessagingPush', :path => sdk_local_path
  pod 'CustomerIOMessagingPushFCM', :path => sdk_local_path
  pod 'CustomerIOMessagingInApp', :path => sdk_local_path

  pod 'FirebaseMessaging', '~> 10.6'

  pod 'SampleAppsCommon', :path => File.join(File.dirname(__FILE__), '../Common')
end

target 'Rich Push Notification Service Extension' do 
  pod 'CustomerIOCommon', :path => sdk_local_path
  pod 'CustomerIOTracking', :path => sdk_local_path
  pod 'CustomerIOMessagingPush', :path => sdk_local_path
  pod 'CustomerIOMessagingPushFCM', :path => sdk_local_path
end 
