platform :ios do  

  before_all do |lane, options|    
    setup_ci
  end

  # Note: I was experiencing issues getting adhoc code signing working for the cocoapods FCM sample app. 
  # For now, we just need to test the app compiles so development code signing is good enough for now until we fix the issue.     
  # For now, do code signing and app compiling using development type. 
  lane :build_app do |arguments|    
    sync_code_signing(
      type: "development"
    )

    build_ios_app(
      export_method: "development",
      configuration: "Debug",
      xcodebuild_formatter: "xcbeautify"
    )
  end 

end 