name: Build one of the sample apps
description: Encapsulate all the logic needed to compile a sample app. 

inputs:
  # If you want to save a new build, pass in this input. If you want to get the latest build, leave this input out.
  apn-or-fcm:
    description: 'Defines which push service to build the sample app for. Either "APN" or "FCM".'
    type: string
    required: true
  sample-app:
    description: 'The name of the sample app to build. Provide name of 1 of the directories in the Apps/ directory. Example: "CocoaPods-FCM"'
    type: string
    required: true
  # The action we use to interact with Fastlane requires a JSON object for arguments, https://github.com/maierj/fastlane-action?tab=readme-ov-file#inputs
  fastlane-build-args:
    description: 'Arguments to pass to the Fastlane build command. Example: "{ "option1": "value1", "option2": "value2" }"'
    type: string
    required: false
    default: '{}'
  customerio-workspace-siteid:
    description: 'The site ID for a workspace in Customer.io to set as default in compiled app, probably a secret.'
    type: string
    required: true 
  customerio-workspace-cdp-api-key:
    description: 'The CDP API key for a workspace in Customer.io to set as default in compiled app, probably a secret.'
    type: string
    required: true
  customerio-workspace-name:
    description: "The name of the workspace used in Customer.io to set as default in compiled app. This makes it easier to know which workspace the app is connected to."
    type: string
    required: true
  customerio-public-sdk-version:
    description: "The public version of Customer.io to use in compiled app. This is used to test public releases of Customer.io SDK in the sample apps."
    type: string
    required: false
    default: ''
  firebase-app-id:
    description: "Firebase App ID used for invite links"
    required: false
    default: ''
  instructions-guide-link:
    description: "Link to instructions guide for the sample app"
    required: false
    default: ''
  GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64:
    description: 'Maps to the secret, GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64. Used for code signing. See the Fastlane config files to learn more.'
    type: string
    required: true
  FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64:
    description: 'Set this input, only if you want to upload app for internal testing. Maps to the secret, FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64. Used for uploading compiled apps for testing. See the Fastlane config files to learn more.'
    type: string
    required: false
    default: ''
  SLACK_WEBHOOK_URL:
    description: "Slack Webhook URL for sample app notifications"
    required: false
    default: ''

outputs:
  app-xcarchive-path:
    description: 'The full relative path to the xcarchive for the built sample app. Example: "Apps/APN-UIKit/build/App.xcarchive"'
    value: ${{ steps.set-action-outputs.outputs.app-xcarchive-path }}
  app-xcarchive-name:
    description: 'The name of the xcarchive for the sample app build. Example: "App.xcarchive"'
    value: ${{ steps.set-action-outputs.outputs.app-xcarchive-name }}

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-ios

    - name: Install CLI tools used in CI script 
      shell: bash
      run: |
        brew install sd # used in CI script as an easier to use sed CLI. Replaces text in files. 
        brew install xcbeautify # used by fastlane for output 
    
    - name: Install tools from Gemfile (ruby language) used for building our apps with 
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true # cache tools to make builds faster in future 
    
    - name: Capture Git Context
      shell: bash
      id: git-context
      run: |
        echo "BRANCH_NAME=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
        COMMIT_HASH="${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}"
        echo "COMMIT_HASH=${COMMIT_HASH:0:7}" >> $GITHUB_ENV
        echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
    
    - name: Setup build environment to prepare for building
      shell: bash
      run: |
        make setup_sample_app app=${{ inputs.sample-app }}
        ENV_FILE="Apps/${{ inputs.sample-app }}/BuildEnvironment.swift"
        sd 'buildTimestamp: TimeInterval = .*' "buildTimestamp: TimeInterval = $(date +%s)" "$ENV_FILE"

        sd 'cdpApiKey: String = \".*\"' "cdpApiKey: String = \"${{ inputs.customerio-workspace-cdp-api-key }}\"" "$ENV_FILE"
        sd 'siteId: String = \".*\"' "siteId: String = \"${{ inputs.customerio-workspace-siteid }}\"" "$ENV_FILE"
        sd 'workspaceName: String = \".*\"' "workspaceName: String = \"${{ inputs.customerio-workspace-name }}\"" "$ENV_FILE"
        if [[ -n "${{ inputs.customerio-public-sdk-version }}" ]]; then
          sd 'sdkVersion: String = \".*\"' "sdkVersion: String = \"${{ inputs.customerio-public-sdk-version }}\"" "$ENV_FILE"
        fi

        sd 'branchName: String = \".*\"' "branchName: String = \"${{ env.BRANCH_NAME }}\"" "$ENV_FILE"
        sd 'commitHash: String = \".*\"' "commitHash: String = \"${{ env.COMMIT_HASH }}\"" "$ENV_FILE"

        LAST_TAG="${LATEST_TAG:-untagged}"
        COMMITS_AHEAD=$(git rev-list $LAST_TAG..HEAD --count 2>/dev/null || echo "untracked")
        sd 'commitsAheadCount: String = \".*\"' "commitsAheadCount: String = \"$COMMITS_AHEAD\"" "$ENV_FILE"

    - name: Does ${{ inputs.sample-app }} use CocoaPods? 
      id: check_podfile_exists
      uses: andstor/file-existence-action@v3
      with:
        files: "Apps/${{ inputs.sample-app }}/Podfile"

    - name: Cache CocoaPods downloaded dependencies for faster builds in the future 
      if: steps.check_podfile_exists.outputs.files_exists == 'true'
      uses: actions/cache@v4
      with:
        path: Apps/${{ inputs.sample-app }}/Pods
        key: ${{ runner.os }}-${{ inputs.sample-app}}-Pods-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.sample-app}}-Pods

    - name: Cache SPM downloaded dependencies for faster builds in the future 
      if: steps.check_podfile_exists.outputs.files_exists == 'false'
      uses: actions/cache@v4
      with:
        path: Apps/${{ inputs.sample-app }}/spm_packages
        key: ${{ runner.os }}-${{ inputs.sample-app}}-SPMPackages-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.sample-app}}-SPMPackages

    - name: Run pod install if using CocoaPods 
      if: steps.check_podfile_exists.outputs.files_exists == 'true'
      shell: bash
      run: make install_cocoapods_dependencies app=${{ inputs.sample-app }}

    - name: Dump GitHub Action metadata because Fastlane uses it. Viewing it here helps debug JSON parsing code in Firebase. 
      shell: bash
      run: cat $GITHUB_EVENT_PATH

    - name: Build app via Fastlane 
      uses: maierj/fastlane-action@v3.1.0
      with:
        lane: "ios build"
        subdirectory: "Apps/${{ inputs.sample-app }}"
        options: ${{ inputs.fastlane-build-args }}
      env: 
        GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64: ${{ inputs.GOOGLE_CLOUD_MATCH_READONLY_SERVICE_ACCOUNT_B64 }}
        FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64: ${{ inputs.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_CREDS_B64 }}

    - name: Determine SDK Version
      shell: bash
      id: determine-sdk-version
      run: |
        sdk_version="${{ inputs.customerio-public-sdk-version }}"
        sdk_version="${sdk_version:-${{ env.SDK_VERSION }}}"
        sdk_version="${sdk_version:-${{ env.LATEST_TAG }}}"
        echo "SDK Version used in app build: $sdk_version"
        echo "APP_SDK_BUILD_VERSION=$sdk_version" >> $GITHUB_ENV

    - name: Send Slack Notification for Sample App Builds
      if: ${{ always() && inputs.apn-or-fcm == 'APN' && inputs.SLACK_WEBHOOK_URL != '' }}
      uses: customerio/mobile-ci-tools/github-actions/slack-notify-sample-app/v1
      with:
        build_status: ${{ job.status }}
        app_icon_emoji: ":ios:"
        app_name: "iOS Native"
        firebase_app_id: ${{ inputs.firebase-app-id }}
        firebase_distribution_groups: ${{ env.firebase_distribution_groups }}
        git_context: "${{ env.BRANCH_NAME }} (${{ env.COMMIT_HASH }})"
        icon_url: "https://pngimg.com/uploads/apple_logo/apple_logo_PNG19687.png"
        instructions_guide_link: ${{ inputs.instructions-guide-link }}
        platform: "ios"
        sdk_name: "iOS Native SDK"
        sdk_version: ${{ env.APP_SDK_BUILD_VERSION }}
        slack_webhook_url: ${{ inputs.SLACK_WEBHOOK_URL }}

    # xcodebuild creates builds that include a timestamp in the name. In order for bloaty to read the build, we need to rename it to a static name.
    - name: Rename the same app build to a static name that we can generate SDK size reports with
      shell: bash
      run: mv Apps/${{ inputs.sample-app }}/build/*.xcarchive Apps/${{ inputs.sample-app }}/build/App.xcarchive 

    - name: Set action output values
      id: set-action-outputs
      shell: bash
      run: |
        echo "app-xcarchive-path=$(echo Apps/${{ inputs.sample-app }}/build/App.xcarchive)" >> $GITHUB_OUTPUT
        echo "app-xcarchive-name=$(echo App.xcarchive)" >> $GITHUB_OUTPUT