name: Lint

on: [pull_request]

jobs:
  assert-formatted:
    name: Assert that code has been linted and formatted before merging
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install swiftformat and swiftlint 
        run: |
          brew update # verifies brew knows latest versions of all CLIs
          brew install swiftformat || brew upgrade swiftformat 
          brew install swiftlint || brew upgrade swiftlint 
      - name: Run swiftformat. Fail if any errors. 
        run: make format && git diff --exit-code
      - name: Run swiftlint. Fail if any errors. 
        run: make lint