name: Lint

on: [pull_request]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint via SwiftLint 
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict