name: Lint

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: customerio/mobile-ci-tools/.github/workflows/ios-lint.yml@main
