name: Lint

on: [pull_request]

concurrency: # If you push a commit while CI already running, cancel it and just run your recent push. 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint via SwiftLint 
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict