name: Lint

on: [pull_request]

jobs:
  assert-formatted:
    name: Assert that code has been linted and formatted before merging
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Deno in order to execute scripts/ 
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run swiftformat. Fail if any errors. 
        run: make format && git diff --exit-code
      - name: Run swiftlint. Fail if any errors. 
        run: make lint