name: PushDP

on: 
  push:
    branches: 
      - aman/migration-cocoapods

jobs:
  Deploy-DP-to-Cocoapods: # This is the job ID, which was missing
    name: Deploy DP to Cocoapods
    runs-on: macos-13
    env:
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    steps:
      - uses: actions/checkout@v3 # Ensures your repository is checked out to run scripts

      - uses: ./.github/actions/setup-ios

      - name: Install cocoapods
        run: gem install cocoapods

      - name: '⚠️ Note: Pushing to cocoapods is flaky. If you see some errors in these logs while deploying, re-run this GitHub Action to try deployment again and it might fix the issue.'
        run: echo ''
        
      - name: Push CustomerIO
        run: ./scripts/push-cocoapod.sh CustomerIO.podspec

