name: Simulate merging a PR 

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  BRANCH_TO_CREATE_SIMULATING_MERGE: "temp-simulate_merge_pr_${{ env.PR_NUMBER }}"

jobs:
  merge-commits-push-branch:
    runs-on: ubuntu-latest
    name: Merge commits push branch 
    permissions: # permissions must match that of a real deployment because auth is tested in dry-run
      contents: write # for pushing commits and tags 
    steps:
    - uses: actions/checkout@v3

    # Help with how to squash and merge a PR: https://stackoverflow.com/a/5201642
    - name: Squash all commits of the current branch into 1 commit 
      run: |
        git fetch --depth=1
        git checkout -b "temp-squash-commits-branch"
        git config user.name "CI Server" && git config user.email "ci-server@customer.io"
        git reset --soft origin/main && git commit -m "${{ github.event.pull_request.title }}"
        git log
    
    - name: Merge squashed commit to main branch to simulate merging PR into main 
      run: |
        git checkout main && git pull && git checkout -b "${{ env.BRANCH_TO_CREATE_SIMULATING_MERGE }}"
        git merge "temp-squash-commits-branch"
        git log
        git branch && git status
        git push -u origin "${{ env.BRANCH_TO_CREATE_SIMULATING_MERGE }}"
    
    - name: Trigger another workflow to test the deployment from new branch 
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: test-deployment.yml
        inputs: '{ "branch_to_checkout": "${{ env.BRANCH_TO_CREATE_SIMULATING_MERGE }}", "pr_number": "${{ env.PR_NUMBER }}" }'