name: Simulate merging a PR 

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  merge-commits-push-branch:
    runs-on: ubuntu-latest
    name: Merge commits push branch 
    permissions: # permissions must match that of a real deployment because auth is tested in dry-run
      contents: write # for pushing commits and tags 
    steps:
    - uses: actions/checkout@v3

    # Help with how to squash and merge a PR: https://stackoverflow.com/a/5201642
    - name: Squash and merge the current pull request to simulate merging this PR 
      run: |
        git fetch --depth=1
        git checkout -b "${{ steps.branch-name.outputs.current_branch }}"
        git config user.email "ci@c.io" && git config user.name "CI Server"
        git reset --soft origin/main && git commit -m "${{ github.event.pull_request.title }}"
        git log
        git checkout main && git pull && git checkout "simulated_merge_pr_${{ github.event.pull_request.number }}"
        git log
        git merge "${{ steps.branch-name.outputs.current_branch }}"
        git log
        git branch && git status