name: Test cocoapods

on: [push, pull_request]

concurrency: # If you push a commit while CI already running, cancel it and just run your recent push.
  group: ${{ github.ref }}
  cancel-in-progress: true

# By testing each in parallel, we can reduce wait time on CI to merge a PR. 
jobs:
  build-cocoapods:
    runs-on: macos-latest
    name: Build ${{ matrix.podspec }}
    strategy:
      matrix:
        podspec: 
        - CustomerIO.podspec
        - CustomerIOCommon.podspec
        - CustomerIOTracking.podspec
        - CustomerIOMessagingPush.podspec
        - CustomerIOMessagingPushFCM.podspec          
        - CustomerIOMessagingPushAPN.podspec
        - CustomerIOMessagingInApp.podspec
    steps:
      - uses: actions/checkout@v3
      - name: Install/update cocoapods 
        run: gem install cocoapods 
      - run: pod --version 
      - run: pod spec lint --allow-warnings ${{ matrix.podspec }}